/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package horaslaborales;

import Inputs.VerifiedAddRegistry;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alejandro
 */
public class AddRegistry extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    Registry registry;
    ManagingRegistry managing;
    ManagingDataUser managingData;
    Sesion user;
    VerifiedAddRegistry verifiedRegistry;
    ArrayList<Turn> turnsUser;

    public AddRegistry(Sesion user) {
        this.user = user;
        initComponents();
        managing = new ManagingRegistry(user);
        managingData = new ManagingDataUser(user);
        preConfigureWindow();

    }

    public AddRegistry(Registry reg, Sesion user) {
        initComponents();
        this.user = user;
        this.registry = reg;
        managing = new ManagingRegistry(user);
        managingData = new ManagingDataUser(user);
        preChargedData();
        preConfigureWindow();

    }

    private int getTimeChooser(JComboBox combo) {
        int select = combo.getSelectedIndex();

        if (select == 0) {
            if (verifiedRegistry.selectTypeDay() == 3 | verifiedRegistry.selectTypeDay() == 4) {
                return 0;
            } else {
                return 24;
            }
        } else {
            return select;
        }
    }

    private void preConfigureWindow() {

        managing.getSalary(salary, user.getUser());

        //Edit Table contents
        
        turnsUser = managingData.getTurns();
        
        for (Turn turn : turnsUser) {
            
            turns.addItem(turn.getNameTurn());
        }

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Tipo Hora", "Cantidad", "Costo"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });

        verifiedRegistry = new VerifiedAddRegistry(this.time1, time2, date1, date2);
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private String nameHours(int i) {
        String[] nameHours = new String[11];
        nameHours[0] = "H. Ordinarias";
        nameHours[1] = "H. Recargo";
        nameHours[2] = "H. Extra Diurna";
        nameHours[3] = "H. Extra Recargo";
        nameHours[4] = "Total Horas Dia 1 ";
        nameHours[5] = "H. Dominical Festivo";
        nameHours[6] = "H. Dominical Festivo Recargo";
        nameHours[7] = "H. Dominical Festivo Ex. Diurno";
        nameHours[8] = "H. Dominical Festivo Ex. Recargo";
        nameHours[9] = "Total Horas Dia 2";
        nameHours[10] = "TOTAL:";

        return nameHours[i];
    }

    private void preChargedData() {
        if (registry != null) {
            this.date1.setDate(registry.getStartDay());
            date1.setSelectableDateRange(registry.getStartDay(), registry.getStartDay());

        }
    }

    private void showData(Calculator calc) {

        if (jTable1.getSize().height > 0) {

        }

        double[] costo = calc.calcularSueldo();
        calc.contT = 0;
        int[] horas = calc.calcularHoras();
        DefaultTableModel table = (DefaultTableModel) this.jTable1.getModel();
        table.setNumRows(0);

        int n = horas.length;

        for (int i = 0; i < n; i++) {

            if (horas[i] != 0) {

                //Mostrar primero info domingo o festivo
                if (n > 5 & verifiedRegistry.selectTypeDay() == 4) {
                    if (i < 5) {

                        if (i != 4) {
                            table.addRow(new Object[]{nameHours(i + 5), horas[i], costo[i]});
                        } else
                            table.addRow(new Object[]{nameHours(i), horas[i], costo[i]});

                    } else {
                        if (i < 9) {
                            table.addRow(new Object[]{nameHours(i - 5), horas[i], costo[i]});
                        } else {
                            table.addRow(new Object[]{nameHours(i), horas[i], costo[i]});
                        }

                    }

                    //Mostrar info turno de dos dias ordinario
                } else if (getTimeChooser(time2) < getTimeChooser(time1) & verifiedRegistry.selectTypeDay() == 1) {

                    if (i > 4 & i < 9) {
                        table.addRow(new Object[]{nameHours(i - 5), horas[i], costo[i]});
                    } else {
                        table.addRow(new Object[]{nameHours(i), horas[i], costo[i]});
                    }

                } else {

                    table.addRow(new Object[]{nameHours(i), horas[i], costo[i]});
                }
            }

        }

    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        salary = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        calculate = new javax.swing.JButton();
        date1 = new com.toedter.calendar.JDateChooser();
        date2 = new com.toedter.calendar.JDateChooser();
        turns = new javax.swing.JComboBox<>();
        saveRegistry = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        startToday = new javax.swing.JCheckBox();
        finishToday = new javax.swing.JCheckBox();
        time1 = new javax.swing.JComboBox<>();
        time2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salary.setEditable(false);
        salary.setBackground(new java.awt.Color(171, 235, 198));
        salary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salaryKeyPressed(evt);
            }
        });
        getContentPane().add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 110, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Sueldo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 70, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Fecha/Hora Fin");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 160, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Fecha/Hora Inicio");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 170, 30));

        jTable1.setBackground(new java.awt.Color(130, 224, 170));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(171, 235, 198));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 480, 110));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Seleccione un turno");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        calculate.setBackground(new java.awt.Color(40, 180, 99));
        calculate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        calculate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Calculator_24px.png"))); // NOI18N
        calculate.setText("Calcular");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });
        getContentPane().add(calculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 120, 40));

        date1.setBackground(new java.awt.Color(171, 235, 198));
        date1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date1PropertyChange(evt);
            }
        });
        getContentPane().add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 110, 30));

        date2.setBackground(new java.awt.Color(171, 235, 198));
        date2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date2PropertyChange(evt);
            }
        });
        getContentPane().add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 110, 30));

        turns.setBackground(new java.awt.Color(171, 235, 198));
        turns.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        turns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnsActionPerformed(evt);
            }
        });
        getContentPane().add(turns, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 270, 30));

        saveRegistry.setBackground(new java.awt.Color(40, 180, 99));
        saveRegistry.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        saveRegistry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Save_24px.png"))); // NOI18N
        saveRegistry.setText("Guardar en Registro");
        saveRegistry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveRegistryActionPerformed(evt);
            }
        });
        getContentPane().add(saveRegistry, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, -1, 40));

        cancel.setBackground(new java.awt.Color(40, 180, 99));
        cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Cancel_24px.png"))); // NOI18N
        cancel.setText("Cancelar");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 130, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("$");
        jLabel6.setAlignmentX(1.0F);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 30, 30));

        startToday.setText("Hoy");
        startToday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTodayActionPerformed(evt);
            }
        });
        getContentPane().add(startToday, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        finishToday.setText("Hoy");
        finishToday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishTodayActionPerformed(evt);
            }
        });
        getContentPane().add(finishToday, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        time1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12 am", "01 am", "02 am", "03 am", "04 am", "05 am", "06 am", "07 am", "08 am", "09 am", "10 am", "11 am", "12 pm", "01 pm", "02 pm", "03 pm", "04 pm", "05 pm", "06 pm", "07 pm", "08 pm", "09 pm", "10 pm", "11 pm" }));
        getContentPane().add(time1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, 30));

        time2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12 am", "01 am", "02 am", "03 am", "04 am", "05 am", "06 am", "07 am", "08 am", "09 am", "10 am", "11 am", "12 pm", "01 pm", "02 pm", "03 pm", "04 pm", "05 pm", "06 pm", "07 pm", "08 pm", "09 pm", "10 pm", "11 pm" }));
        time2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time2ActionPerformed(evt);
            }
        });
        getContentPane().add(time2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/maxresdefault.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
        Calculator calc;
        jTable1.removeAll();
        jTable1.updateUI();
        verifiedRegistry.verifiedDates();

        if (verifiedRegistry.verifiedEntries()) {

            String sal = this.salary.getText().replaceAll(" ", "");

            double i = Double.parseDouble(sal);

            calc = new Calculator(getTimeChooser(time1), getTimeChooser(time2), (int) i);
            System.out.println(verifiedRegistry.selectTypeDay());
            calc.setDia(verifiedRegistry.selectTypeDay());
            showData(calc);

        }

    }//GEN-LAST:event_calculateActionPerformed

    private void salaryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salaryKeyPressed

    }//GEN-LAST:event_salaryKeyPressed

    private void turnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnsActionPerformed
        // TODO add your handling code here:

        int numTurn = turns.getSelectedIndex();
       
        if(numTurn>=0){
            
            time1.setSelectedItem(turnsUser.get(numTurn-1).getHourStart());
            time2.setSelectedItem(turnsUser.get(numTurn-1).getHourFinish());
            
            System.out.println(turnsUser.get(numTurn-1).getHourStart());
        }
        
    }//GEN-LAST:event_turnsActionPerformed

    private void saveRegistryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveRegistryActionPerformed
        // TODO add your handling code here:
        verifiedRegistry.verifiedDates();
        if (verifiedRegistry.verifiedEntries()) {

            String sal = this.salary.getText().replace(" ", "");
            double i = Double.parseDouble(sal);

            Calculator calc = new Calculator(getTimeChooser(time1), getTimeChooser(time2),
                    (int) i);
            calc.setDia(verifiedRegistry.selectTypeDay());

            if (registry == null) {

                boolean h = managing.saveRegistry(this.date1, this.date2, calc);
                if (h) {
                    dispose();
                }

            } else {

                managing.updateRegistry(date1, date2, calc);

            }
            //managing.updateLastSalary(salary, "prueba");
            //dispose();

        }
    }//GEN-LAST:event_saveRegistryActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void startTodayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTodayActionPerformed
        // TODO add your handling code here:

        Calendar calendarNow;
        calendarNow = Calendar.getInstance();
        this.date1.setCalendar(calendarNow);

    }//GEN-LAST:event_startTodayActionPerformed

    private void finishTodayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishTodayActionPerformed
        // TODO add your handling code here:
        Calendar calendarNow;
        calendarNow = Calendar.getInstance();
        this.date2.setCalendar(calendarNow);
    }//GEN-LAST:event_finishTodayActionPerformed

    private void date1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date1PropertyChange
        // TODO add your handling code here:

        if (this.date2.getCalendar() == null & verifiedRegistry != null) {
            if (verifiedRegistry.selectTypeDay() > 1) {
                Calendar c = date1.getCalendar();
                c.roll(Calendar.DAY_OF_MONTH, 1);
                date2.setCalendar(c);
            }

        }
    }//GEN-LAST:event_date1PropertyChange

    private void date2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date2PropertyChange
        // TODO add your handling code here:
        /*if (this.jDateChooser1.getCalendar() == null) {
            
            if (selectTypeDay.getSelectedIndex() > 1) {
                Calendar c = jDateChooser2.getCalendar();
                c.add(Calendar.DAY_OF_MONTH, -1);
                jDateChooser2.setCalendar(c);
            }

        }*/
    }//GEN-LAST:event_date2PropertyChange

    private void time2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time2ActionPerformed
        // TODO add your handling code here:
        verifiedRegistry.verifiedDates();
    }//GEN-LAST:event_time2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddRegistry.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddRegistry.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddRegistry.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddRegistry.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AddRegistry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calculate;
    private javax.swing.JButton cancel;
    private com.toedter.calendar.JDateChooser date1;
    private com.toedter.calendar.JDateChooser date2;
    private javax.swing.JCheckBox finishToday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField salary;
    private javax.swing.JButton saveRegistry;
    private javax.swing.JCheckBox startToday;
    private javax.swing.JComboBox<String> time1;
    private javax.swing.JComboBox<String> time2;
    private javax.swing.JComboBox<String> turns;
    // End of variables declaration//GEN-END:variables
}
