/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package horaslaborales;

import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.awt.event.WindowStateListener;
import java.io.File;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.application.Application;
import javafx.application.Platform;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.paint.Color;
import javafx.stage.FileChooser;
import javafx.stage.Stage;
import javafx.stage.Window;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alejandro
 */
public class ViewHistory extends javax.swing.JFrame {

    /**
     * Creates new form ViewHistory
     */
    File file;

    public ViewHistory() {
        initComponents();

        ManagingRegistry.chargueMonthRegistries(this.selectMounth, jTable1);

    }

    private void initFX(JFXPanel fxPanel) {
        // This method is invoked on the JavaFX thread
        Scene scene = createScene();
        fxPanel.setScene(scene);
    }

    
    private  Scene createScene() {
        Group root = new Group();
        Scene scene = new Scene(root, Color.ALICEBLUE);

        FileChooser fileChooser = new FileChooser();
        file = fileChooser.showSaveDialog(scene.getWindow());
        if(file!=null){
            ManagingRegistry.saveRegistryToExcel(jTable1, file.getAbsolutePath());
        }
        
        
        return (scene);
    }

    public void updateTable() {
        java.awt.event.ActionEvent evt = null;
        selectMounthActionPerformed(evt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddRegistry = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        exportToExcel = new javax.swing.JButton();
        selectMounth = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        editRegistry = new javax.swing.JButton();
        deleteRegistry = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddRegistry.setBackground(new java.awt.Color(40, 180, 99));
        AddRegistry.setText("Agregar Registro");
        AddRegistry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRegistryActionPerformed(evt);
            }
        });
        getContentPane().add(AddRegistry, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 170, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fecha", "Horas Ordinarias", "Horas R. Nocturno", "H. Extras Diurno", "H. Extras Nocturno", "Sueldo dia"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 900, 320));

        exportToExcel.setBackground(new java.awt.Color(40, 180, 99));
        exportToExcel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exportToExcel.setText("Exportar a Excel");
        exportToExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportToExcelActionPerformed(evt);
            }
        });
        getContentPane().add(exportToExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 500, 150, 40));

        selectMounth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectMounthActionPerformed(evt);
            }
        });
        getContentPane().add(selectMounth, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 60, 150, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Seleccionar mes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, 130, -1));

        editRegistry.setBackground(new java.awt.Color(40, 180, 99));
        editRegistry.setText("Editar Registro");
        editRegistry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRegistryActionPerformed(evt);
            }
        });
        getContentPane().add(editRegistry, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 170, 40));

        deleteRegistry.setBackground(new java.awt.Color(40, 180, 99));
        deleteRegistry.setText("Eliminar Registro");
        deleteRegistry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRegistryActionPerformed(evt);
            }
        });
        getContentPane().add(deleteRegistry, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 560, 170, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/maxresdefault.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 1, 990, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exportToExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportToExcelActionPerformed
        // TODO add your handling code here:
       final JFXPanel fxPanel = new JFXPanel();
        this.add(fxPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0));
        Platform.runLater(new Runnable() {
            @Override
            public void run() {
                initFX(fxPanel);
            }
        });

        //show();
        //

    }//GEN-LAST:event_exportToExcelActionPerformed

    private void selectMounthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectMounthActionPerformed
        // TODO add your handling code here:

        ManagingRegistry.chargueMonthRegistries(selectMounth, jTable1);
    }//GEN-LAST:event_selectMounthActionPerformed

    private void editRegistryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRegistryActionPerformed
        // TODO add your handling code here:
        int rowSelected = jTable1.getSelectedRow();

        if (rowSelected != -1) {
            DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
            Vector v = (Vector) m.getDataVector().get(rowSelected);
            AddRegistry editRegistry = new AddRegistry(ManagingRegistry.searchRegistry((String) v.get(0)));
            editRegistry.setVisible(rootPaneCheckingEnabled);
            editRegistry.addWindowListener(new ClosedWindowEvent(this));
            editRegistry.setLocationRelativeTo(null);

        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione el Registro en la tabla");
        }

    }//GEN-LAST:event_editRegistryActionPerformed

    private void AddRegistryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRegistryActionPerformed
        // TODO add your handling code here:
        AddRegistry window = new AddRegistry();
        window.setVisible(true);
        window.setLocationRelativeTo(null);
        window.addWindowListener(new ClosedWindowEvent(this));

    }//GEN-LAST:event_AddRegistryActionPerformed

    private void deleteRegistryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRegistryActionPerformed
        // TODO add your handling code here:
        int rowSelected = jTable1.getSelectedRow();

        if (rowSelected != -1) {
            DefaultTableModel m = (DefaultTableModel) jTable1.getModel();
            Vector v = (Vector) m.getDataVector().get(rowSelected);
            ManagingRegistry.deleteRegistry((String) v.get(0));
            this.updateTable();

        } else {
            JOptionPane.showMessageDialog(rootPane, "Seleccione el Registro en la tabla");
        }
    }//GEN-LAST:event_deleteRegistryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRegistry;
    private javax.swing.JLabel background;
    private javax.swing.JButton deleteRegistry;
    private javax.swing.JButton editRegistry;
    private javax.swing.JButton exportToExcel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> selectMounth;
    // End of variables declaration//GEN-END:variables
}
