/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Alejandro
 */
public class CalendarHistoryPane extends javax.swing.JPanel {

    /**
     * Creates new form CalendarHistoryPane
     */
    public CalendarHistoryPane() {
        initComponents();
        p1.removeAll();
        p1.add(new TwoTurnsPane(), new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 90));
        p1.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p111 = new javax.swing.JPanel();
        jLabel320 = new javax.swing.JLabel();
        jLabel321 = new javax.swing.JLabel();
        jLabel322 = new javax.swing.JLabel();
        jLabel323 = new javax.swing.JLabel();
        p112 = new javax.swing.JPanel();
        jLabel324 = new javax.swing.JLabel();
        jLabel325 = new javax.swing.JLabel();
        jLabel326 = new javax.swing.JLabel();
        jLabel327 = new javax.swing.JLabel();
        p113 = new javax.swing.JPanel();
        jLabel328 = new javax.swing.JLabel();
        jLabel329 = new javax.swing.JLabel();
        jLabel330 = new javax.swing.JLabel();
        jLabel331 = new javax.swing.JLabel();
        p114 = new javax.swing.JPanel();
        jLabel332 = new javax.swing.JLabel();
        jLabel333 = new javax.swing.JLabel();
        jLabel334 = new javax.swing.JLabel();
        jLabel335 = new javax.swing.JLabel();
        p115 = new javax.swing.JPanel();
        jLabel336 = new javax.swing.JLabel();
        jLabel337 = new javax.swing.JLabel();
        jLabel338 = new javax.swing.JLabel();
        jLabel339 = new javax.swing.JLabel();
        p116 = new javax.swing.JPanel();
        jLabel340 = new javax.swing.JLabel();
        jLabel341 = new javax.swing.JLabel();
        jLabel342 = new javax.swing.JLabel();
        jLabel343 = new javax.swing.JLabel();
        p117 = new javax.swing.JPanel();
        jLabel344 = new javax.swing.JLabel();
        jLabel345 = new javax.swing.JLabel();
        jLabel346 = new javax.swing.JLabel();
        jLabel347 = new javax.swing.JLabel();
        p132 = new javax.swing.JPanel();
        jLabel404 = new javax.swing.JLabel();
        jLabel405 = new javax.swing.JLabel();
        jLabel406 = new javax.swing.JLabel();
        jLabel407 = new javax.swing.JLabel();
        p133 = new javax.swing.JPanel();
        jLabel408 = new javax.swing.JLabel();
        jLabel409 = new javax.swing.JLabel();
        jLabel410 = new javax.swing.JLabel();
        jLabel411 = new javax.swing.JLabel();
        p134 = new javax.swing.JPanel();
        jLabel412 = new javax.swing.JLabel();
        jLabel413 = new javax.swing.JLabel();
        jLabel414 = new javax.swing.JLabel();
        jLabel415 = new javax.swing.JLabel();
        p135 = new javax.swing.JPanel();
        jLabel416 = new javax.swing.JLabel();
        jLabel417 = new javax.swing.JLabel();
        jLabel418 = new javax.swing.JLabel();
        jLabel419 = new javax.swing.JLabel();
        p136 = new javax.swing.JPanel();
        jLabel420 = new javax.swing.JLabel();
        jLabel421 = new javax.swing.JLabel();
        jLabel422 = new javax.swing.JLabel();
        jLabel423 = new javax.swing.JLabel();
        p137 = new javax.swing.JPanel();
        jLabel424 = new javax.swing.JLabel();
        jLabel425 = new javax.swing.JLabel();
        jLabel426 = new javax.swing.JLabel();
        jLabel427 = new javax.swing.JLabel();
        p138 = new javax.swing.JPanel();
        jLabel428 = new javax.swing.JLabel();
        jLabel429 = new javax.swing.JLabel();
        jLabel430 = new javax.swing.JLabel();
        jLabel431 = new javax.swing.JLabel();
        p139 = new javax.swing.JPanel();
        jLabel432 = new javax.swing.JLabel();
        jLabel433 = new javax.swing.JLabel();
        jLabel434 = new javax.swing.JLabel();
        jLabel435 = new javax.swing.JLabel();
        p140 = new javax.swing.JPanel();
        jLabel436 = new javax.swing.JLabel();
        jLabel437 = new javax.swing.JLabel();
        jLabel438 = new javax.swing.JLabel();
        jLabel439 = new javax.swing.JLabel();
        p141 = new javax.swing.JPanel();
        jLabel440 = new javax.swing.JLabel();
        jLabel441 = new javax.swing.JLabel();
        jLabel442 = new javax.swing.JLabel();
        jLabel443 = new javax.swing.JLabel();
        p142 = new javax.swing.JPanel();
        jLabel444 = new javax.swing.JLabel();
        jLabel445 = new javax.swing.JLabel();
        jLabel446 = new javax.swing.JLabel();
        jLabel447 = new javax.swing.JLabel();
        p143 = new javax.swing.JPanel();
        jLabel448 = new javax.swing.JLabel();
        jLabel449 = new javax.swing.JLabel();
        jLabel450 = new javax.swing.JLabel();
        jLabel451 = new javax.swing.JLabel();
        p144 = new javax.swing.JPanel();
        jLabel452 = new javax.swing.JLabel();
        jLabel453 = new javax.swing.JLabel();
        jLabel454 = new javax.swing.JLabel();
        jLabel455 = new javax.swing.JLabel();
        p145 = new javax.swing.JPanel();
        jLabel456 = new javax.swing.JLabel();
        jLabel457 = new javax.swing.JLabel();
        jLabel458 = new javax.swing.JLabel();
        jLabel459 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        p1 = new javax.swing.JPanel();
        d1 = new javax.swing.JLabel();
        t1 = new javax.swing.JLabel();
        m1 = new javax.swing.JLabel();
        h1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        p7 = new javax.swing.JPanel();
        d7 = new javax.swing.JLabel();
        t7 = new javax.swing.JLabel();
        m7 = new javax.swing.JLabel();
        h7 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        d2 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        m2 = new javax.swing.JLabel();
        h2 = new javax.swing.JLabel();
        p3 = new javax.swing.JPanel();
        d3 = new javax.swing.JLabel();
        t3 = new javax.swing.JLabel();
        m3 = new javax.swing.JLabel();
        h3 = new javax.swing.JLabel();
        p4 = new javax.swing.JPanel();
        d4 = new javax.swing.JLabel();
        t4 = new javax.swing.JLabel();
        m4 = new javax.swing.JLabel();
        h4 = new javax.swing.JLabel();
        p5 = new javax.swing.JPanel();
        d5 = new javax.swing.JLabel();
        t5 = new javax.swing.JLabel();
        m5 = new javax.swing.JLabel();
        h5 = new javax.swing.JLabel();
        p6 = new javax.swing.JPanel();
        d6 = new javax.swing.JLabel();
        t6 = new javax.swing.JLabel();
        m6 = new javax.swing.JLabel();
        h6 = new javax.swing.JLabel();
        p13 = new javax.swing.JPanel();
        d13 = new javax.swing.JLabel();
        t13 = new javax.swing.JLabel();
        m13 = new javax.swing.JLabel();
        h13 = new javax.swing.JLabel();
        p12 = new javax.swing.JPanel();
        d12 = new javax.swing.JLabel();
        t12 = new javax.swing.JLabel();
        m12 = new javax.swing.JLabel();
        h12 = new javax.swing.JLabel();
        p14 = new javax.swing.JPanel();
        d14 = new javax.swing.JLabel();
        t14 = new javax.swing.JLabel();
        m14 = new javax.swing.JLabel();
        h14 = new javax.swing.JLabel();
        p9 = new javax.swing.JPanel();
        d9 = new javax.swing.JLabel();
        t9 = new javax.swing.JLabel();
        m9 = new javax.swing.JLabel();
        h9 = new javax.swing.JLabel();
        p8 = new javax.swing.JPanel();
        d8 = new javax.swing.JLabel();
        t8 = new javax.swing.JLabel();
        m8 = new javax.swing.JLabel();
        h8 = new javax.swing.JLabel();
        p10 = new javax.swing.JPanel();
        d10 = new javax.swing.JLabel();
        t10 = new javax.swing.JLabel();
        m10 = new javax.swing.JLabel();
        h10 = new javax.swing.JLabel();
        p11 = new javax.swing.JPanel();
        d11 = new javax.swing.JLabel();
        t11 = new javax.swing.JLabel();
        m11 = new javax.swing.JLabel();
        h11 = new javax.swing.JLabel();
        p20 = new javax.swing.JPanel();
        d20 = new javax.swing.JLabel();
        t20 = new javax.swing.JLabel();
        m20 = new javax.swing.JLabel();
        h20 = new javax.swing.JLabel();
        p19 = new javax.swing.JPanel();
        d19 = new javax.swing.JLabel();
        t19 = new javax.swing.JLabel();
        m19 = new javax.swing.JLabel();
        h19 = new javax.swing.JLabel();
        p18 = new javax.swing.JPanel();
        d18 = new javax.swing.JLabel();
        t18 = new javax.swing.JLabel();
        m18 = new javax.swing.JLabel();
        h18 = new javax.swing.JLabel();
        p15 = new javax.swing.JPanel();
        d15 = new javax.swing.JLabel();
        t15 = new javax.swing.JLabel();
        m15 = new javax.swing.JLabel();
        h15 = new javax.swing.JLabel();
        p17 = new javax.swing.JPanel();
        d17 = new javax.swing.JLabel();
        t17 = new javax.swing.JLabel();
        m17 = new javax.swing.JLabel();
        h17 = new javax.swing.JLabel();
        p21 = new javax.swing.JPanel();
        d21 = new javax.swing.JLabel();
        t21 = new javax.swing.JLabel();
        m21 = new javax.swing.JLabel();
        h21 = new javax.swing.JLabel();
        p16 = new javax.swing.JPanel();
        d16 = new javax.swing.JLabel();
        t16 = new javax.swing.JLabel();
        m16 = new javax.swing.JLabel();
        h16 = new javax.swing.JLabel();
        p27 = new javax.swing.JPanel();
        d27 = new javax.swing.JLabel();
        t27 = new javax.swing.JLabel();
        m27 = new javax.swing.JLabel();
        h27 = new javax.swing.JLabel();
        p25 = new javax.swing.JPanel();
        d25 = new javax.swing.JLabel();
        t25 = new javax.swing.JLabel();
        m25 = new javax.swing.JLabel();
        h25 = new javax.swing.JLabel();
        p22 = new javax.swing.JPanel();
        d22 = new javax.swing.JLabel();
        t22 = new javax.swing.JLabel();
        m22 = new javax.swing.JLabel();
        h22 = new javax.swing.JLabel();
        p28 = new javax.swing.JPanel();
        d28 = new javax.swing.JLabel();
        t28 = new javax.swing.JLabel();
        m28 = new javax.swing.JLabel();
        h28 = new javax.swing.JLabel();
        p26 = new javax.swing.JPanel();
        d26 = new javax.swing.JLabel();
        t26 = new javax.swing.JLabel();
        m26 = new javax.swing.JLabel();
        h26 = new javax.swing.JLabel();
        p23 = new javax.swing.JPanel();
        d23 = new javax.swing.JLabel();
        t23 = new javax.swing.JLabel();
        m23 = new javax.swing.JLabel();
        h23 = new javax.swing.JLabel();
        p24 = new javax.swing.JPanel();
        d24 = new javax.swing.JLabel();
        t24 = new javax.swing.JLabel();
        m24 = new javax.swing.JLabel();
        h24 = new javax.swing.JLabel();
        p29 = new javax.swing.JPanel();
        d29 = new javax.swing.JLabel();
        t29 = new javax.swing.JLabel();
        m29 = new javax.swing.JLabel();
        h29 = new javax.swing.JLabel();
        p30 = new javax.swing.JPanel();
        d30 = new javax.swing.JLabel();
        t30 = new javax.swing.JLabel();
        m30 = new javax.swing.JLabel();
        h30 = new javax.swing.JLabel();
        p31 = new javax.swing.JPanel();
        d31 = new javax.swing.JLabel();
        t31 = new javax.swing.JLabel();
        m31 = new javax.swing.JLabel();
        h31 = new javax.swing.JLabel();
        p32 = new javax.swing.JPanel();
        d32 = new javax.swing.JLabel();
        t32 = new javax.swing.JLabel();
        m32 = new javax.swing.JLabel();
        h32 = new javax.swing.JLabel();
        p33 = new javax.swing.JPanel();
        d33 = new javax.swing.JLabel();
        t33 = new javax.swing.JLabel();
        m33 = new javax.swing.JLabel();
        h33 = new javax.swing.JLabel();
        p34 = new javax.swing.JPanel();
        d34 = new javax.swing.JLabel();
        t34 = new javax.swing.JLabel();
        m34 = new javax.swing.JLabel();
        h34 = new javax.swing.JLabel();
        p35 = new javax.swing.JPanel();
        d35 = new javax.swing.JLabel();
        t35 = new javax.swing.JLabel();
        m35 = new javax.swing.JLabel();
        h35 = new javax.swing.JLabel();
        p36 = new javax.swing.JPanel();
        d36 = new javax.swing.JLabel();
        t36 = new javax.swing.JLabel();
        m36 = new javax.swing.JLabel();
        h36 = new javax.swing.JLabel();
        p37 = new javax.swing.JPanel();
        d37 = new javax.swing.JLabel();
        t37 = new javax.swing.JLabel();
        m37 = new javax.swing.JLabel();
        h37 = new javax.swing.JLabel();
        p38 = new javax.swing.JPanel();
        d38 = new javax.swing.JLabel();
        t38 = new javax.swing.JLabel();
        m38 = new javax.swing.JLabel();
        h38 = new javax.swing.JLabel();
        p39 = new javax.swing.JPanel();
        d39 = new javax.swing.JLabel();
        t39 = new javax.swing.JLabel();
        m39 = new javax.swing.JLabel();
        h39 = new javax.swing.JLabel();
        p40 = new javax.swing.JPanel();
        d40 = new javax.swing.JLabel();
        t40 = new javax.swing.JLabel();
        m40 = new javax.swing.JLabel();
        h40 = new javax.swing.JLabel();
        p41 = new javax.swing.JPanel();
        d41 = new javax.swing.JLabel();
        t41 = new javax.swing.JLabel();
        m41 = new javax.swing.JLabel();
        h41 = new javax.swing.JLabel();
        p42 = new javax.swing.JPanel();
        d42 = new javax.swing.JLabel();
        t42 = new javax.swing.JLabel();
        m42 = new javax.swing.JLabel();
        h42 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        p111.setBackground(new java.awt.Color(255, 255, 255));
        p111.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p111.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel320.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel320.setText("1");
        p111.add(jLabel320, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel321.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel321.setText("T1");
        p111.add(jLabel321, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel322.setText("$ 36.000");
        p111.add(jLabel322, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel323.setText("02:00 pm - 11:00pm");
        p111.add(jLabel323, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        p112.setBackground(new java.awt.Color(255, 255, 255));
        p112.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p112.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel324.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel324.setText("1");
        p112.add(jLabel324, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel325.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel325.setText("T1");
        p112.add(jLabel325, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel326.setText("$ 36.000");
        p112.add(jLabel326, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel327.setText("02:00 pm - 11:00pm");
        p112.add(jLabel327, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        p113.setBackground(new java.awt.Color(255, 255, 255));
        p113.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p113.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel328.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel328.setText("1");
        p113.add(jLabel328, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel329.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel329.setText("T1");
        p113.add(jLabel329, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel330.setText("$ 36.000");
        p113.add(jLabel330, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel331.setText("02:00 pm - 11:00pm");
        p113.add(jLabel331, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        p114.setBackground(new java.awt.Color(255, 255, 255));
        p114.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p114.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel332.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel332.setText("1");
        p114.add(jLabel332, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel333.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel333.setText("T1");
        p114.add(jLabel333, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel334.setText("$ 36.000");
        p114.add(jLabel334, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel335.setText("02:00 pm - 11:00pm");
        p114.add(jLabel335, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        p115.setBackground(new java.awt.Color(255, 255, 255));
        p115.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p115.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel336.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel336.setText("1");
        p115.add(jLabel336, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel337.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel337.setText("T1");
        p115.add(jLabel337, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel338.setText("$ 36.000");
        p115.add(jLabel338, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel339.setText("02:00 pm - 11:00pm");
        p115.add(jLabel339, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        p116.setBackground(new java.awt.Color(255, 255, 255));
        p116.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p116.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel340.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel340.setText("1");
        p116.add(jLabel340, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel341.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel341.setText("T1");
        p116.add(jLabel341, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel342.setText("$ 36.000");
        p116.add(jLabel342, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel343.setText("02:00 pm - 11:00pm");
        p116.add(jLabel343, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        p117.setBackground(new java.awt.Color(255, 255, 255));
        p117.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p117.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel344.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel344.setText("1");
        p117.add(jLabel344, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel345.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel345.setText("T1");
        p117.add(jLabel345, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel346.setText("$ 36.000");
        p117.add(jLabel346, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel347.setText("02:00 pm - 11:00pm");
        p117.add(jLabel347, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        p132.setBackground(new java.awt.Color(255, 255, 255));
        p132.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p132.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel404.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel404.setText("1");
        p132.add(jLabel404, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel405.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel405.setText("T1");
        p132.add(jLabel405, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel406.setText("$ 36.000");
        p132.add(jLabel406, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel407.setText("02:00 pm - 11:00pm");
        p132.add(jLabel407, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        p133.setBackground(new java.awt.Color(255, 255, 255));
        p133.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p133.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel408.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel408.setText("1");
        p133.add(jLabel408, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel409.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel409.setText("T1");
        p133.add(jLabel409, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel410.setText("$ 36.000");
        p133.add(jLabel410, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel411.setText("02:00 pm - 11:00pm");
        p133.add(jLabel411, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        p134.setBackground(new java.awt.Color(255, 255, 255));
        p134.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p134.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel412.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel412.setText("1");
        p134.add(jLabel412, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel413.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel413.setText("T1");
        p134.add(jLabel413, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel414.setText("$ 36.000");
        p134.add(jLabel414, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel415.setText("02:00 pm - 11:00pm");
        p134.add(jLabel415, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        p135.setBackground(new java.awt.Color(255, 255, 255));
        p135.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p135.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel416.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel416.setText("1");
        p135.add(jLabel416, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel417.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel417.setText("T1");
        p135.add(jLabel417, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel418.setText("$ 36.000");
        p135.add(jLabel418, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel419.setText("02:00 pm - 11:00pm");
        p135.add(jLabel419, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        p136.setBackground(new java.awt.Color(255, 255, 255));
        p136.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p136.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel420.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel420.setText("1");
        p136.add(jLabel420, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel421.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel421.setText("T1");
        p136.add(jLabel421, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel422.setText("$ 36.000");
        p136.add(jLabel422, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel423.setText("02:00 pm - 11:00pm");
        p136.add(jLabel423, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        p137.setBackground(new java.awt.Color(255, 255, 255));
        p137.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p137.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel424.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel424.setText("1");
        p137.add(jLabel424, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel425.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel425.setText("T1");
        p137.add(jLabel425, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel426.setText("$ 36.000");
        p137.add(jLabel426, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel427.setText("02:00 pm - 11:00pm");
        p137.add(jLabel427, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        p138.setBackground(new java.awt.Color(255, 255, 255));
        p138.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p138.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel428.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel428.setText("1");
        p138.add(jLabel428, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel429.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel429.setText("T1");
        p138.add(jLabel429, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel430.setText("$ 36.000");
        p138.add(jLabel430, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel431.setText("02:00 pm - 11:00pm");
        p138.add(jLabel431, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        p139.setBackground(new java.awt.Color(255, 255, 255));
        p139.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p139.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel432.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel432.setText("1");
        p139.add(jLabel432, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel433.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel433.setText("T1");
        p139.add(jLabel433, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel434.setText("$ 36.000");
        p139.add(jLabel434, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel435.setText("02:00 pm - 11:00pm");
        p139.add(jLabel435, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        p140.setBackground(new java.awt.Color(255, 255, 255));
        p140.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p140.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel436.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel436.setText("1");
        p140.add(jLabel436, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel437.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel437.setText("T1");
        p140.add(jLabel437, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel438.setText("$ 36.000");
        p140.add(jLabel438, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel439.setText("02:00 pm - 11:00pm");
        p140.add(jLabel439, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        p141.setBackground(new java.awt.Color(255, 255, 255));
        p141.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p141.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel440.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel440.setText("1");
        p141.add(jLabel440, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel441.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel441.setText("T1");
        p141.add(jLabel441, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel442.setText("$ 36.000");
        p141.add(jLabel442, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel443.setText("02:00 pm - 11:00pm");
        p141.add(jLabel443, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        p142.setBackground(new java.awt.Color(255, 255, 255));
        p142.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p142.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel444.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel444.setText("1");
        p142.add(jLabel444, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel445.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel445.setText("T1");
        p142.add(jLabel445, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel446.setText("$ 36.000");
        p142.add(jLabel446, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel447.setText("02:00 pm - 11:00pm");
        p142.add(jLabel447, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        p143.setBackground(new java.awt.Color(255, 255, 255));
        p143.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p143.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel448.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel448.setText("1");
        p143.add(jLabel448, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel449.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel449.setText("T1");
        p143.add(jLabel449, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel450.setText("$ 36.000");
        p143.add(jLabel450, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel451.setText("02:00 pm - 11:00pm");
        p143.add(jLabel451, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        p144.setBackground(new java.awt.Color(255, 255, 255));
        p144.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p144.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel452.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel452.setText("1");
        p144.add(jLabel452, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel453.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel453.setText("T1");
        p144.add(jLabel453, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel454.setText("$ 36.000");
        p144.add(jLabel454, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel455.setText("02:00 pm - 11:00pm");
        p144.add(jLabel455, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        p145.setBackground(new java.awt.Color(255, 255, 255));
        p145.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p145.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel456.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel456.setText("1");
        p145.add(jLabel456, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel457.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel457.setText("T1");
        p145.add(jLabel457, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel458.setText("$ 36.000");
        p145.add(jLabel458, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel459.setText("02:00 pm - 11:00pm");
        p145.add(jLabel459, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setMinimumSize(new java.awt.Dimension(840, 570));
        jPanel2.setPreferredSize(new java.awt.Dimension(840, 570));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p1.setBackground(new java.awt.Color(255, 255, 255));
        p1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d1.setText("1");
        p1.add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t1.setText("T1");
        p1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m1.setText("$ 36.000");
        p1.add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h1.setText("02:00 pm - 11:00pm");
        p1.add(h1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 120, -1));

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("SABADO");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 80, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("DOMINGO");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("LUNES");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 60, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("MARTES");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 80, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("MIERCOLES");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 100, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("JUEVES");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 70, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("VIERNES");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 80, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 10, 30));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 10, 30));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 0, 0, 30));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 10, 30));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 10, 30));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 10, 30));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 10, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 30));

        p7.setBackground(new java.awt.Color(255, 255, 255));
        p7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d7.setText("1");
        p7.add(d7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t7.setText("T1");
        p7.add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m7.setText("$ 36.000");
        p7.add(m7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h7.setText("02:00 pm - 11:00pm");
        p7.add(h7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 120, -1));

        p2.setBackground(new java.awt.Color(255, 255, 255));
        p2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d2.setText("1");
        p2.add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t2.setText("T1");
        p2.add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m2.setText("$ 36.000");
        p2.add(m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h2.setText("02:00 pm - 11:00pm");
        p2.add(h2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        p3.setBackground(new java.awt.Color(255, 255, 255));
        p3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d3.setText("1");
        p3.add(d3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t3.setText("T1");
        p3.add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m3.setText("$ 36.000");
        p3.add(m3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h3.setText("02:00 pm - 11:00pm");
        p3.add(h3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        p4.setBackground(new java.awt.Color(255, 255, 255));
        p4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d4.setText("1");
        p4.add(d4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t4.setText("T1");
        p4.add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m4.setText("$ 36.000");
        p4.add(m4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h4.setText("02:00 pm - 11:00pm");
        p4.add(h4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        p5.setBackground(new java.awt.Color(255, 255, 255));
        p5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d5.setText("1");
        p5.add(d5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t5.setText("T1");
        p5.add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m5.setText("$ 36.000");
        p5.add(m5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h5.setText("02:00 pm - 11:00pm");
        p5.add(h5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        p6.setBackground(new java.awt.Color(255, 255, 255));
        p6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d6.setText("1");
        p6.add(d6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t6.setText("T1");
        p6.add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m6.setText("$ 36.000");
        p6.add(m6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h6.setText("02:00 pm - 11:00pm");
        p6.add(h6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        p13.setBackground(new java.awt.Color(255, 255, 255));
        p13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d13.setText("1");
        p13.add(d13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t13.setText("T1");
        p13.add(t13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m13.setText("$ 36.000");
        p13.add(m13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h13.setText("02:00 pm - 11:00pm");
        p13.add(h13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p13, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

        p12.setBackground(new java.awt.Color(255, 255, 255));
        p12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d12.setText("1");
        p12.add(d12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t12.setText("T1");
        p12.add(t12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m12.setText("$ 36.000");
        p12.add(m12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h12.setText("02:00 pm - 11:00pm");
        p12.add(h12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        p14.setBackground(new java.awt.Color(255, 255, 255));
        p14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d14.setText("1");
        p14.add(d14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t14.setText("T1");
        p14.add(t14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m14.setText("$ 36.000");
        p14.add(m14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h14.setText("02:00 pm - 11:00pm");
        p14.add(h14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, -1, -1));

        p9.setBackground(new java.awt.Color(255, 255, 255));
        p9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d9.setText("1");
        p9.add(d9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t9.setText("T1");
        p9.add(t9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m9.setText("$ 36.000");
        p9.add(m9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h9.setText("02:00 pm - 11:00pm");
        p9.add(h9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        p8.setBackground(new java.awt.Color(255, 255, 255));
        p8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d8.setText("1");
        p8.add(d8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t8.setText("T1");
        p8.add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m8.setText("$ 36.000");
        p8.add(m8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h8.setText("02:00 pm - 11:00pm");
        p8.add(h8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        p10.setBackground(new java.awt.Color(255, 255, 255));
        p10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d10.setText("1");
        p10.add(d10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t10.setText("T1");
        p10.add(t10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m10.setText("$ 36.000");
        p10.add(m10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h10.setText("02:00 pm - 11:00pm");
        p10.add(h10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        p11.setBackground(new java.awt.Color(255, 255, 255));
        p11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d11.setText("1");
        p11.add(d11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t11.setText("T1");
        p11.add(t11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m11.setText("$ 36.000");
        p11.add(m11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h11.setText("02:00 pm - 11:00pm");
        p11.add(h11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        p20.setBackground(new java.awt.Color(255, 255, 255));
        p20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d20.setText("1");
        p20.add(d20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t20.setText("T1");
        p20.add(t20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m20.setText("$ 36.000");
        p20.add(m20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h20.setText("02:00 pm - 11:00pm");
        p20.add(h20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p20, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, -1, -1));

        p19.setBackground(new java.awt.Color(255, 255, 255));
        p19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d19.setText("1");
        p19.add(d19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t19.setText("T1");
        p19.add(t19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m19.setText("$ 36.000");
        p19.add(m19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h19.setText("02:00 pm - 11:00pm");
        p19.add(h19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, -1));

        p18.setBackground(new java.awt.Color(255, 255, 255));
        p18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d18.setText("1");
        p18.add(d18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t18.setText("T1");
        p18.add(t18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m18.setText("$ 36.000");
        p18.add(m18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h18.setText("02:00 pm - 11:00pm");
        p18.add(h18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        p15.setBackground(new java.awt.Color(255, 255, 255));
        p15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d15.setText("1");
        p15.add(d15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t15.setText("T1");
        p15.add(t15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m15.setText("$ 36.000");
        p15.add(m15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h15.setText("02:00 pm - 11:00pm");
        p15.add(h15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        p17.setBackground(new java.awt.Color(255, 255, 255));
        p17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d17.setText("1");
        p17.add(d17, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t17.setText("T1");
        p17.add(t17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m17.setText("$ 36.000");
        p17.add(m17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h17.setText("02:00 pm - 11:00pm");
        p17.add(h17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        p21.setBackground(new java.awt.Color(255, 255, 255));
        p21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d21.setText("1");
        p21.add(d21, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t21.setText("T1");
        p21.add(t21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m21.setText("$ 36.000");
        p21.add(m21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h21.setText("02:00 pm - 11:00pm");
        p21.add(h21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p21, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 210, -1, -1));

        p16.setBackground(new java.awt.Color(255, 255, 255));
        p16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d16.setText("1");
        p16.add(d16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t16.setText("T1");
        p16.add(t16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m16.setText("$ 36.000");
        p16.add(m16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h16.setText("02:00 pm - 11:00pm");
        p16.add(h16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        p27.setBackground(new java.awt.Color(255, 255, 255));
        p27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d27.setText("1");
        p27.add(d27, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t27.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t27.setText("T1");
        p27.add(t27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m27.setText("$ 36.000");
        p27.add(m27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h27.setText("02:00 pm - 11:00pm");
        p27.add(h27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p27, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, -1, -1));

        p25.setBackground(new java.awt.Color(255, 255, 255));
        p25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d25.setText("1");
        p25.add(d25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t25.setText("T1");
        p25.add(t25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m25.setText("$ 36.000");
        p25.add(m25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h25.setText("02:00 pm - 11:00pm");
        p25.add(h25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p25, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, -1, -1));

        p22.setBackground(new java.awt.Color(255, 255, 255));
        p22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d22.setText("1");
        p22.add(d22, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t22.setText("T1");
        p22.add(t22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m22.setText("$ 36.000");
        p22.add(m22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h22.setText("02:00 pm - 11:00pm");
        p22.add(h22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        p28.setBackground(new java.awt.Color(255, 255, 255));
        p28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d28.setText("1");
        p28.add(d28, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t28.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t28.setText("T1");
        p28.add(t28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m28.setText("$ 36.000");
        p28.add(m28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h28.setText("02:00 pm - 11:00pm");
        p28.add(h28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p28, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, -1, -1));

        p26.setBackground(new java.awt.Color(255, 255, 255));
        p26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d26.setText("1");
        p26.add(d26, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t26.setText("T1");
        p26.add(t26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m26.setText("$ 36.000");
        p26.add(m26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h26.setText("02:00 pm - 11:00pm");
        p26.add(h26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p26, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, -1));

        p23.setBackground(new java.awt.Color(255, 255, 255));
        p23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d23.setText("1");
        p23.add(d23, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t23.setText("T1");
        p23.add(t23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m23.setText("$ 36.000");
        p23.add(m23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h23.setText("02:00 pm - 11:00pm");
        p23.add(h23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, -1, -1));

        p24.setBackground(new java.awt.Color(255, 255, 255));
        p24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d24.setText("1");
        p24.add(d24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t24.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t24.setText("T1");
        p24.add(t24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m24.setText("$ 36.000");
        p24.add(m24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h24.setText("02:00 pm - 11:00pm");
        p24.add(h24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p24, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, -1, -1));

        p29.setBackground(new java.awt.Color(255, 255, 255));
        p29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d29.setText("1");
        p29.add(d29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t29.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t29.setText("T1");
        p29.add(t29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m29.setText("$ 36.000");
        p29.add(m29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h29.setText("02:00 pm - 11:00pm");
        p29.add(h29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, -1));

        p30.setBackground(new java.awt.Color(255, 255, 255));
        p30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d30.setText("1");
        p30.add(d30, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t30.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t30.setText("T1");
        p30.add(t30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m30.setText("$ 36.000");
        p30.add(m30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h30.setText("02:00 pm - 11:00pm");
        p30.add(h30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p30, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        p31.setBackground(new java.awt.Color(255, 255, 255));
        p31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d31.setText("1");
        p31.add(d31, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t31.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t31.setText("T1");
        p31.add(t31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m31.setText("$ 36.000");
        p31.add(m31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h31.setText("02:00 pm - 11:00pm");
        p31.add(h31, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p31, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        p32.setBackground(new java.awt.Color(255, 255, 255));
        p32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d32.setText("1");
        p32.add(d32, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t32.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t32.setText("T1");
        p32.add(t32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m32.setText("$ 36.000");
        p32.add(m32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h32.setText("02:00 pm - 11:00pm");
        p32.add(h32, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p32, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, -1, -1));

        p33.setBackground(new java.awt.Color(255, 255, 255));
        p33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d33.setText("1");
        p33.add(d33, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t33.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t33.setText("T1");
        p33.add(t33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m33.setText("$ 36.000");
        p33.add(m33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h33.setText("02:00 pm - 11:00pm");
        p33.add(h33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p33, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));

        p34.setBackground(new java.awt.Color(255, 255, 255));
        p34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d34.setText("1");
        p34.add(d34, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t34.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t34.setText("T1");
        p34.add(t34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m34.setText("$ 36.000");
        p34.add(m34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h34.setText("02:00 pm - 11:00pm");
        p34.add(h34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p34, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, -1, -1));

        p35.setBackground(new java.awt.Color(255, 255, 255));
        p35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d35.setText("1");
        p35.add(d35, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t35.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t35.setText("T1");
        p35.add(t35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m35.setText("$ 36.000");
        p35.add(m35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h35.setText("02:00 pm - 11:00pm");
        p35.add(h35, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p35, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, -1, -1));

        p36.setBackground(new java.awt.Color(255, 255, 255));
        p36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d36.setText("1");
        p36.add(d36, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t36.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t36.setText("T1");
        p36.add(t36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m36.setText("$ 36.000");
        p36.add(m36, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h36.setText("02:00 pm - 11:00pm");
        p36.add(h36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, -1, -1));

        p37.setBackground(new java.awt.Color(255, 255, 255));
        p37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d37.setText("1");
        p37.add(d37, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t37.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t37.setText("T1");
        p37.add(t37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m37.setText("$ 36.000");
        p37.add(m37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h37.setText("02:00 pm - 11:00pm");
        p37.add(h37, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p37, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, -1, -1));

        p38.setBackground(new java.awt.Color(255, 255, 255));
        p38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p38.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d38.setText("1");
        p38.add(d38, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t38.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t38.setText("T1");
        p38.add(t38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m38.setText("$ 36.000");
        p38.add(m38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h38.setText("02:00 pm - 11:00pm");
        p38.add(h38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p38, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 480, -1, -1));

        p39.setBackground(new java.awt.Color(255, 255, 255));
        p39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p39.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d39.setText("1");
        p39.add(d39, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t39.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t39.setText("T1");
        p39.add(t39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m39.setText("$ 36.000");
        p39.add(m39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h39.setText("02:00 pm - 11:00pm");
        p39.add(h39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p39, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, -1, -1));

        p40.setBackground(new java.awt.Color(255, 255, 255));
        p40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p40.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d40.setText("1");
        p40.add(d40, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t40.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t40.setText("T1");
        p40.add(t40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m40.setText("$ 36.000");
        p40.add(m40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h40.setText("02:00 pm - 11:00pm");
        p40.add(h40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p40, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, -1, -1));

        p41.setBackground(new java.awt.Color(255, 255, 255));
        p41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p41.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d41.setText("1");
        p41.add(d41, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t41.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t41.setText("T1");
        p41.add(t41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m41.setText("$ 36.000");
        p41.add(m41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h41.setText("02:00 pm - 11:00pm");
        p41.add(h41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p41, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, -1, -1));

        p42.setBackground(new java.awt.Color(255, 255, 255));
        p42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p42.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        d42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        d42.setText("1");
        p42.add(d42, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        t42.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t42.setText("T1");
        p42.add(t42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        m42.setText("$ 36.000");
        p42.add(m42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        h42.setText("02:00 pm - 11:00pm");
        p42.add(h42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jPanel2.add(p42, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, -1, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 570));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Junio de 2018");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 210, 30));

        jButton1.setBackground(new java.awt.Color(51, 204, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Forward_30px.png"))); // NOI18N
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 50, 30));

        jButton2.setBackground(new java.awt.Color(51, 204, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Back_30px.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 50, 30));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel d1;
    private javax.swing.JLabel d10;
    private javax.swing.JLabel d11;
    private javax.swing.JLabel d12;
    private javax.swing.JLabel d13;
    private javax.swing.JLabel d14;
    private javax.swing.JLabel d15;
    private javax.swing.JLabel d16;
    private javax.swing.JLabel d17;
    private javax.swing.JLabel d18;
    private javax.swing.JLabel d19;
    private javax.swing.JLabel d2;
    private javax.swing.JLabel d20;
    private javax.swing.JLabel d21;
    private javax.swing.JLabel d22;
    private javax.swing.JLabel d23;
    private javax.swing.JLabel d24;
    private javax.swing.JLabel d25;
    private javax.swing.JLabel d26;
    private javax.swing.JLabel d27;
    private javax.swing.JLabel d28;
    private javax.swing.JLabel d29;
    private javax.swing.JLabel d3;
    private javax.swing.JLabel d30;
    private javax.swing.JLabel d31;
    private javax.swing.JLabel d32;
    private javax.swing.JLabel d33;
    private javax.swing.JLabel d34;
    private javax.swing.JLabel d35;
    private javax.swing.JLabel d36;
    private javax.swing.JLabel d37;
    private javax.swing.JLabel d38;
    private javax.swing.JLabel d39;
    private javax.swing.JLabel d4;
    private javax.swing.JLabel d40;
    private javax.swing.JLabel d41;
    private javax.swing.JLabel d42;
    private javax.swing.JLabel d5;
    private javax.swing.JLabel d6;
    private javax.swing.JLabel d7;
    private javax.swing.JLabel d8;
    private javax.swing.JLabel d9;
    private javax.swing.JLabel h1;
    private javax.swing.JLabel h10;
    private javax.swing.JLabel h11;
    private javax.swing.JLabel h12;
    private javax.swing.JLabel h13;
    private javax.swing.JLabel h14;
    private javax.swing.JLabel h15;
    private javax.swing.JLabel h16;
    private javax.swing.JLabel h17;
    private javax.swing.JLabel h18;
    private javax.swing.JLabel h19;
    private javax.swing.JLabel h2;
    private javax.swing.JLabel h20;
    private javax.swing.JLabel h21;
    private javax.swing.JLabel h22;
    private javax.swing.JLabel h23;
    private javax.swing.JLabel h24;
    private javax.swing.JLabel h25;
    private javax.swing.JLabel h26;
    private javax.swing.JLabel h27;
    private javax.swing.JLabel h28;
    private javax.swing.JLabel h29;
    private javax.swing.JLabel h3;
    private javax.swing.JLabel h30;
    private javax.swing.JLabel h31;
    private javax.swing.JLabel h32;
    private javax.swing.JLabel h33;
    private javax.swing.JLabel h34;
    private javax.swing.JLabel h35;
    private javax.swing.JLabel h36;
    private javax.swing.JLabel h37;
    private javax.swing.JLabel h38;
    private javax.swing.JLabel h39;
    private javax.swing.JLabel h4;
    private javax.swing.JLabel h40;
    private javax.swing.JLabel h41;
    private javax.swing.JLabel h42;
    private javax.swing.JLabel h5;
    private javax.swing.JLabel h6;
    private javax.swing.JLabel h7;
    private javax.swing.JLabel h8;
    private javax.swing.JLabel h9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel320;
    private javax.swing.JLabel jLabel321;
    private javax.swing.JLabel jLabel322;
    private javax.swing.JLabel jLabel323;
    private javax.swing.JLabel jLabel324;
    private javax.swing.JLabel jLabel325;
    private javax.swing.JLabel jLabel326;
    private javax.swing.JLabel jLabel327;
    private javax.swing.JLabel jLabel328;
    private javax.swing.JLabel jLabel329;
    private javax.swing.JLabel jLabel330;
    private javax.swing.JLabel jLabel331;
    private javax.swing.JLabel jLabel332;
    private javax.swing.JLabel jLabel333;
    private javax.swing.JLabel jLabel334;
    private javax.swing.JLabel jLabel335;
    private javax.swing.JLabel jLabel336;
    private javax.swing.JLabel jLabel337;
    private javax.swing.JLabel jLabel338;
    private javax.swing.JLabel jLabel339;
    private javax.swing.JLabel jLabel340;
    private javax.swing.JLabel jLabel341;
    private javax.swing.JLabel jLabel342;
    private javax.swing.JLabel jLabel343;
    private javax.swing.JLabel jLabel344;
    private javax.swing.JLabel jLabel345;
    private javax.swing.JLabel jLabel346;
    private javax.swing.JLabel jLabel347;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel404;
    private javax.swing.JLabel jLabel405;
    private javax.swing.JLabel jLabel406;
    private javax.swing.JLabel jLabel407;
    private javax.swing.JLabel jLabel408;
    private javax.swing.JLabel jLabel409;
    private javax.swing.JLabel jLabel410;
    private javax.swing.JLabel jLabel411;
    private javax.swing.JLabel jLabel412;
    private javax.swing.JLabel jLabel413;
    private javax.swing.JLabel jLabel414;
    private javax.swing.JLabel jLabel415;
    private javax.swing.JLabel jLabel416;
    private javax.swing.JLabel jLabel417;
    private javax.swing.JLabel jLabel418;
    private javax.swing.JLabel jLabel419;
    private javax.swing.JLabel jLabel420;
    private javax.swing.JLabel jLabel421;
    private javax.swing.JLabel jLabel422;
    private javax.swing.JLabel jLabel423;
    private javax.swing.JLabel jLabel424;
    private javax.swing.JLabel jLabel425;
    private javax.swing.JLabel jLabel426;
    private javax.swing.JLabel jLabel427;
    private javax.swing.JLabel jLabel428;
    private javax.swing.JLabel jLabel429;
    private javax.swing.JLabel jLabel430;
    private javax.swing.JLabel jLabel431;
    private javax.swing.JLabel jLabel432;
    private javax.swing.JLabel jLabel433;
    private javax.swing.JLabel jLabel434;
    private javax.swing.JLabel jLabel435;
    private javax.swing.JLabel jLabel436;
    private javax.swing.JLabel jLabel437;
    private javax.swing.JLabel jLabel438;
    private javax.swing.JLabel jLabel439;
    private javax.swing.JLabel jLabel440;
    private javax.swing.JLabel jLabel441;
    private javax.swing.JLabel jLabel442;
    private javax.swing.JLabel jLabel443;
    private javax.swing.JLabel jLabel444;
    private javax.swing.JLabel jLabel445;
    private javax.swing.JLabel jLabel446;
    private javax.swing.JLabel jLabel447;
    private javax.swing.JLabel jLabel448;
    private javax.swing.JLabel jLabel449;
    private javax.swing.JLabel jLabel450;
    private javax.swing.JLabel jLabel451;
    private javax.swing.JLabel jLabel452;
    private javax.swing.JLabel jLabel453;
    private javax.swing.JLabel jLabel454;
    private javax.swing.JLabel jLabel455;
    private javax.swing.JLabel jLabel456;
    private javax.swing.JLabel jLabel457;
    private javax.swing.JLabel jLabel458;
    private javax.swing.JLabel jLabel459;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel m1;
    private javax.swing.JLabel m10;
    private javax.swing.JLabel m11;
    private javax.swing.JLabel m12;
    private javax.swing.JLabel m13;
    private javax.swing.JLabel m14;
    private javax.swing.JLabel m15;
    private javax.swing.JLabel m16;
    private javax.swing.JLabel m17;
    private javax.swing.JLabel m18;
    private javax.swing.JLabel m19;
    private javax.swing.JLabel m2;
    private javax.swing.JLabel m20;
    private javax.swing.JLabel m21;
    private javax.swing.JLabel m22;
    private javax.swing.JLabel m23;
    private javax.swing.JLabel m24;
    private javax.swing.JLabel m25;
    private javax.swing.JLabel m26;
    private javax.swing.JLabel m27;
    private javax.swing.JLabel m28;
    private javax.swing.JLabel m29;
    private javax.swing.JLabel m3;
    private javax.swing.JLabel m30;
    private javax.swing.JLabel m31;
    private javax.swing.JLabel m32;
    private javax.swing.JLabel m33;
    private javax.swing.JLabel m34;
    private javax.swing.JLabel m35;
    private javax.swing.JLabel m36;
    private javax.swing.JLabel m37;
    private javax.swing.JLabel m38;
    private javax.swing.JLabel m39;
    private javax.swing.JLabel m4;
    private javax.swing.JLabel m40;
    private javax.swing.JLabel m41;
    private javax.swing.JLabel m42;
    private javax.swing.JLabel m5;
    private javax.swing.JLabel m6;
    private javax.swing.JLabel m7;
    private javax.swing.JLabel m8;
    private javax.swing.JLabel m9;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p10;
    private javax.swing.JPanel p11;
    private javax.swing.JPanel p111;
    private javax.swing.JPanel p112;
    private javax.swing.JPanel p113;
    private javax.swing.JPanel p114;
    private javax.swing.JPanel p115;
    private javax.swing.JPanel p116;
    private javax.swing.JPanel p117;
    private javax.swing.JPanel p12;
    private javax.swing.JPanel p13;
    private javax.swing.JPanel p132;
    private javax.swing.JPanel p133;
    private javax.swing.JPanel p134;
    private javax.swing.JPanel p135;
    private javax.swing.JPanel p136;
    private javax.swing.JPanel p137;
    private javax.swing.JPanel p138;
    private javax.swing.JPanel p139;
    private javax.swing.JPanel p14;
    private javax.swing.JPanel p140;
    private javax.swing.JPanel p141;
    private javax.swing.JPanel p142;
    private javax.swing.JPanel p143;
    private javax.swing.JPanel p144;
    private javax.swing.JPanel p145;
    private javax.swing.JPanel p15;
    private javax.swing.JPanel p16;
    private javax.swing.JPanel p17;
    private javax.swing.JPanel p18;
    private javax.swing.JPanel p19;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p20;
    private javax.swing.JPanel p21;
    private javax.swing.JPanel p22;
    private javax.swing.JPanel p23;
    private javax.swing.JPanel p24;
    private javax.swing.JPanel p25;
    private javax.swing.JPanel p26;
    private javax.swing.JPanel p27;
    private javax.swing.JPanel p28;
    private javax.swing.JPanel p29;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p30;
    private javax.swing.JPanel p31;
    private javax.swing.JPanel p32;
    private javax.swing.JPanel p33;
    private javax.swing.JPanel p34;
    private javax.swing.JPanel p35;
    private javax.swing.JPanel p36;
    private javax.swing.JPanel p37;
    private javax.swing.JPanel p38;
    private javax.swing.JPanel p39;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel p40;
    private javax.swing.JPanel p41;
    private javax.swing.JPanel p42;
    private javax.swing.JPanel p5;
    private javax.swing.JPanel p6;
    private javax.swing.JPanel p7;
    private javax.swing.JPanel p8;
    private javax.swing.JPanel p9;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t10;
    private javax.swing.JLabel t11;
    private javax.swing.JLabel t12;
    private javax.swing.JLabel t13;
    private javax.swing.JLabel t14;
    private javax.swing.JLabel t15;
    private javax.swing.JLabel t16;
    private javax.swing.JLabel t17;
    private javax.swing.JLabel t18;
    private javax.swing.JLabel t19;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t20;
    private javax.swing.JLabel t21;
    private javax.swing.JLabel t22;
    private javax.swing.JLabel t23;
    private javax.swing.JLabel t24;
    private javax.swing.JLabel t25;
    private javax.swing.JLabel t26;
    private javax.swing.JLabel t27;
    private javax.swing.JLabel t28;
    private javax.swing.JLabel t29;
    private javax.swing.JLabel t3;
    private javax.swing.JLabel t30;
    private javax.swing.JLabel t31;
    private javax.swing.JLabel t32;
    private javax.swing.JLabel t33;
    private javax.swing.JLabel t34;
    private javax.swing.JLabel t35;
    private javax.swing.JLabel t36;
    private javax.swing.JLabel t37;
    private javax.swing.JLabel t38;
    private javax.swing.JLabel t39;
    private javax.swing.JLabel t4;
    private javax.swing.JLabel t40;
    private javax.swing.JLabel t41;
    private javax.swing.JLabel t42;
    private javax.swing.JLabel t5;
    private javax.swing.JLabel t6;
    private javax.swing.JLabel t7;
    private javax.swing.JLabel t8;
    private javax.swing.JLabel t9;
    // End of variables declaration//GEN-END:variables
}
