/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Alejandro
 */
public class CalendarHistoryPane extends javax.swing.JPanel {

    /**
     * Creates new form CalendarHistoryPane
     */
    public CalendarHistoryPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        p43 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        p44 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        p46 = new javax.swing.JPanel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        p45 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        p49 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        p48 = new javax.swing.JPanel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        p47 = new javax.swing.JPanel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        p50 = new javax.swing.JPanel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        p51 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        p52 = new javax.swing.JPanel();
        jLabel84 = new javax.swing.JLabel();
        jLabel85 = new javax.swing.JLabel();
        jLabel86 = new javax.swing.JLabel();
        jLabel87 = new javax.swing.JLabel();
        p54 = new javax.swing.JPanel();
        jLabel92 = new javax.swing.JLabel();
        jLabel93 = new javax.swing.JLabel();
        jLabel94 = new javax.swing.JLabel();
        jLabel95 = new javax.swing.JLabel();
        p53 = new javax.swing.JPanel();
        jLabel88 = new javax.swing.JLabel();
        jLabel89 = new javax.swing.JLabel();
        jLabel90 = new javax.swing.JLabel();
        jLabel91 = new javax.swing.JLabel();
        p55 = new javax.swing.JPanel();
        jLabel96 = new javax.swing.JLabel();
        jLabel97 = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jLabel99 = new javax.swing.JLabel();
        p56 = new javax.swing.JPanel();
        jLabel100 = new javax.swing.JLabel();
        jLabel101 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        jLabel103 = new javax.swing.JLabel();
        p57 = new javax.swing.JPanel();
        jLabel104 = new javax.swing.JLabel();
        jLabel105 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel107 = new javax.swing.JLabel();
        p59 = new javax.swing.JPanel();
        jLabel112 = new javax.swing.JLabel();
        jLabel113 = new javax.swing.JLabel();
        jLabel114 = new javax.swing.JLabel();
        jLabel115 = new javax.swing.JLabel();
        p60 = new javax.swing.JPanel();
        jLabel116 = new javax.swing.JLabel();
        jLabel117 = new javax.swing.JLabel();
        jLabel118 = new javax.swing.JLabel();
        jLabel119 = new javax.swing.JLabel();
        p64 = new javax.swing.JPanel();
        jLabel132 = new javax.swing.JLabel();
        jLabel133 = new javax.swing.JLabel();
        jLabel134 = new javax.swing.JLabel();
        jLabel135 = new javax.swing.JLabel();
        p67 = new javax.swing.JPanel();
        jLabel144 = new javax.swing.JLabel();
        jLabel145 = new javax.swing.JLabel();
        jLabel146 = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();
        p58 = new javax.swing.JPanel();
        jLabel108 = new javax.swing.JLabel();
        jLabel109 = new javax.swing.JLabel();
        jLabel110 = new javax.swing.JLabel();
        jLabel111 = new javax.swing.JLabel();
        p66 = new javax.swing.JPanel();
        jLabel140 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        jLabel143 = new javax.swing.JLabel();
        p65 = new javax.swing.JPanel();
        jLabel136 = new javax.swing.JLabel();
        jLabel137 = new javax.swing.JLabel();
        jLabel138 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        p69 = new javax.swing.JPanel();
        jLabel152 = new javax.swing.JLabel();
        jLabel153 = new javax.swing.JLabel();
        jLabel154 = new javax.swing.JLabel();
        jLabel155 = new javax.swing.JLabel();
        p62 = new javax.swing.JPanel();
        jLabel124 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel126 = new javax.swing.JLabel();
        jLabel127 = new javax.swing.JLabel();
        p63 = new javax.swing.JPanel();
        jLabel128 = new javax.swing.JLabel();
        jLabel129 = new javax.swing.JLabel();
        jLabel130 = new javax.swing.JLabel();
        jLabel131 = new javax.swing.JLabel();
        p70 = new javax.swing.JPanel();
        jLabel156 = new javax.swing.JLabel();
        jLabel157 = new javax.swing.JLabel();
        jLabel158 = new javax.swing.JLabel();
        jLabel159 = new javax.swing.JLabel();
        p61 = new javax.swing.JPanel();
        jLabel120 = new javax.swing.JLabel();
        jLabel121 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jLabel123 = new javax.swing.JLabel();
        p68 = new javax.swing.JPanel();
        jLabel148 = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        jLabel150 = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();
        p71 = new javax.swing.JPanel();
        jLabel160 = new javax.swing.JLabel();
        jLabel161 = new javax.swing.JLabel();
        jLabel162 = new javax.swing.JLabel();
        jLabel163 = new javax.swing.JLabel();
        p72 = new javax.swing.JPanel();
        jLabel164 = new javax.swing.JLabel();
        jLabel165 = new javax.swing.JLabel();
        jLabel166 = new javax.swing.JLabel();
        jLabel167 = new javax.swing.JLabel();
        p73 = new javax.swing.JPanel();
        jLabel168 = new javax.swing.JLabel();
        jLabel169 = new javax.swing.JLabel();
        jLabel170 = new javax.swing.JLabel();
        jLabel171 = new javax.swing.JLabel();
        p74 = new javax.swing.JPanel();
        jLabel172 = new javax.swing.JLabel();
        jLabel173 = new javax.swing.JLabel();
        jLabel174 = new javax.swing.JLabel();
        jLabel175 = new javax.swing.JLabel();
        p75 = new javax.swing.JPanel();
        jLabel176 = new javax.swing.JLabel();
        jLabel177 = new javax.swing.JLabel();
        jLabel178 = new javax.swing.JLabel();
        jLabel179 = new javax.swing.JLabel();
        p76 = new javax.swing.JPanel();
        jLabel180 = new javax.swing.JLabel();
        jLabel181 = new javax.swing.JLabel();
        jLabel182 = new javax.swing.JLabel();
        jLabel183 = new javax.swing.JLabel();
        p77 = new javax.swing.JPanel();
        jLabel184 = new javax.swing.JLabel();
        jLabel185 = new javax.swing.JLabel();
        jLabel186 = new javax.swing.JLabel();
        jLabel187 = new javax.swing.JLabel();
        p78 = new javax.swing.JPanel();
        jLabel188 = new javax.swing.JLabel();
        jLabel189 = new javax.swing.JLabel();
        jLabel190 = new javax.swing.JLabel();
        jLabel191 = new javax.swing.JLabel();
        p79 = new javax.swing.JPanel();
        jLabel192 = new javax.swing.JLabel();
        jLabel193 = new javax.swing.JLabel();
        jLabel194 = new javax.swing.JLabel();
        jLabel195 = new javax.swing.JLabel();
        p80 = new javax.swing.JPanel();
        jLabel196 = new javax.swing.JLabel();
        jLabel197 = new javax.swing.JLabel();
        jLabel198 = new javax.swing.JLabel();
        jLabel199 = new javax.swing.JLabel();
        p81 = new javax.swing.JPanel();
        jLabel200 = new javax.swing.JLabel();
        jLabel201 = new javax.swing.JLabel();
        jLabel202 = new javax.swing.JLabel();
        jLabel203 = new javax.swing.JLabel();
        p82 = new javax.swing.JPanel();
        jLabel204 = new javax.swing.JLabel();
        jLabel205 = new javax.swing.JLabel();
        jLabel206 = new javax.swing.JLabel();
        jLabel207 = new javax.swing.JLabel();
        p83 = new javax.swing.JPanel();
        jLabel208 = new javax.swing.JLabel();
        jLabel209 = new javax.swing.JLabel();
        jLabel210 = new javax.swing.JLabel();
        jLabel211 = new javax.swing.JLabel();
        p84 = new javax.swing.JPanel();
        jLabel212 = new javax.swing.JLabel();
        jLabel213 = new javax.swing.JLabel();
        jLabel214 = new javax.swing.JLabel();
        jLabel215 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p43.setBackground(new java.awt.Color(255, 255, 255));
        p43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p43.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel48.setText("1");
        p43.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel49.setText("T1");
        p43.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel50.setText("$ 36.000");
        p43.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel51.setText("02:00 pm - 11:00pm");
        p43.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p43, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 110, 90));

        p44.setBackground(new java.awt.Color(255, 255, 255));
        p44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p44.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel52.setText("1");
        p44.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel53.setText("T1");
        p44.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel54.setText("$ 36.000");
        p44.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel55.setText("02:00 pm - 11:00pm");
        p44.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 110, 90));

        p46.setBackground(new java.awt.Color(255, 255, 255));
        p46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p46.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel60.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel60.setText("1");
        p46.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel61.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel61.setText("T1");
        p46.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel62.setText("$ 36.000");
        p46.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel63.setText("02:00 pm - 11:00pm");
        p46.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p46, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        p45.setBackground(new java.awt.Color(255, 255, 255));
        p45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p45.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel56.setText("1");
        p45.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel57.setText("T1");
        p45.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel58.setText("$ 36.000");
        p45.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel59.setText("02:00 pm - 11:00pm");
        p45.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p45, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        p49.setBackground(new java.awt.Color(255, 255, 255));
        p49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p49.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel72.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel72.setText("1");
        p49.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel73.setText("T1");
        p49.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel74.setText("$ 36.000");
        p49.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel75.setText("02:00 pm - 11:00pm");
        p49.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 110, 20));

        jPanel2.add(p49, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, -1));

        p48.setBackground(new java.awt.Color(255, 255, 255));
        p48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p48.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel68.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel68.setText("1");
        p48.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel69.setText("T1");
        p48.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel70.setText("$ 36.000");
        p48.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel71.setText("02:00 pm - 11:00pm");
        p48.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 110, 20));

        jPanel2.add(p48, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        p47.setBackground(new java.awt.Color(255, 255, 255));
        p47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p47.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel64.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel64.setText("1");
        p47.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel65.setText("T1");
        p47.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel66.setText("$ 36.000");
        p47.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel67.setText("02:00 pm - 11:00pm");
        p47.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p47, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        p50.setBackground(new java.awt.Color(255, 255, 255));
        p50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p50.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel76.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel76.setText("1");
        p50.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel77.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel77.setText("T1");
        p50.add(jLabel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel78.setText("$ 36.000");
        p50.add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel79.setText("02:00 pm - 11:00pm");
        p50.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p50, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        p51.setBackground(new java.awt.Color(255, 255, 255));
        p51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p51.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel80.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel80.setText("1");
        p51.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel81.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel81.setText("T1");
        p51.add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel82.setText("$ 36.000");
        p51.add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel83.setText("02:00 pm - 11:00pm");
        p51.add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p51, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        p52.setBackground(new java.awt.Color(255, 255, 255));
        p52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p52.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel84.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel84.setText("1");
        p52.add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel85.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel85.setText("T1");
        p52.add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel86.setText("$ 36.000");
        p52.add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel87.setText("02:00 pm - 11:00pm");
        p52.add(jLabel87, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p52, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, -1));

        p54.setBackground(new java.awt.Color(255, 255, 255));
        p54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p54.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel92.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel92.setText("1");
        p54.add(jLabel92, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel93.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel93.setText("T1");
        p54.add(jLabel93, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel94.setText("$ 36.000");
        p54.add(jLabel94, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel95.setText("02:00 pm - 11:00pm");
        p54.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p54, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, -1, -1));

        p53.setBackground(new java.awt.Color(255, 255, 255));
        p53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p53.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel88.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel88.setText("1");
        p53.add(jLabel88, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel89.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel89.setText("T1");
        p53.add(jLabel89, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel90.setText("$ 36.000");
        p53.add(jLabel90, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel91.setText("02:00 pm - 11:00pm");
        p53.add(jLabel91, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p53, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        p55.setBackground(new java.awt.Color(255, 255, 255));
        p55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p55.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel96.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel96.setText("1");
        p55.add(jLabel96, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel97.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel97.setText("T1");
        p55.add(jLabel97, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel98.setText("$ 36.000");
        p55.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel99.setText("02:00 pm - 11:00pm");
        p55.add(jLabel99, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p55, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));

        p56.setBackground(new java.awt.Color(255, 255, 255));
        p56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p56.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel100.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel100.setText("1");
        p56.add(jLabel100, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel101.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel101.setText("T1");
        p56.add(jLabel101, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel102.setText("$ 36.000");
        p56.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel103.setText("02:00 pm - 11:00pm");
        p56.add(jLabel103, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p56, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        p57.setBackground(new java.awt.Color(255, 255, 255));
        p57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p57.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel104.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel104.setText("1");
        p57.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel105.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel105.setText("T1");
        p57.add(jLabel105, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel106.setText("$ 36.000");
        p57.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel107.setText("02:00 pm - 11:00pm");
        p57.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p57, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        p59.setBackground(new java.awt.Color(255, 255, 255));
        p59.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p59.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel112.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel112.setText("1");
        p59.add(jLabel112, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel113.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel113.setText("T1");
        p59.add(jLabel113, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel114.setText("$ 36.000");
        p59.add(jLabel114, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel115.setText("02:00 pm - 11:00pm");
        p59.add(jLabel115, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p59, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        p60.setBackground(new java.awt.Color(255, 255, 255));
        p60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p60.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel116.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel116.setText("1");
        p60.add(jLabel116, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel117.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel117.setText("T1");
        p60.add(jLabel117, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel118.setText("$ 36.000");
        p60.add(jLabel118, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel119.setText("02:00 pm - 11:00pm");
        p60.add(jLabel119, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p60, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        p64.setBackground(new java.awt.Color(255, 255, 255));
        p64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p64.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel132.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel132.setText("1");
        p64.add(jLabel132, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel133.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel133.setText("T1");
        p64.add(jLabel133, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel134.setText("$ 36.000");
        p64.add(jLabel134, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel135.setText("02:00 pm - 11:00pm");
        p64.add(jLabel135, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p64, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, -1, -1));

        p67.setBackground(new java.awt.Color(255, 255, 255));
        p67.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p67.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel144.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel144.setText("1");
        p67.add(jLabel144, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel145.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel145.setText("T1");
        p67.add(jLabel145, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel146.setText("$ 36.000");
        p67.add(jLabel146, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel147.setText("02:00 pm - 11:00pm");
        p67.add(jLabel147, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p67, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, -1, -1));

        p58.setBackground(new java.awt.Color(255, 255, 255));
        p58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p58.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel108.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel108.setText("1");
        p58.add(jLabel108, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel109.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel109.setText("T1");
        p58.add(jLabel109, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel110.setText("$ 36.000");
        p58.add(jLabel110, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel111.setText("02:00 pm - 11:00pm");
        p58.add(jLabel111, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p58, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        p66.setBackground(new java.awt.Color(255, 255, 255));
        p66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p66.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel140.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel140.setText("1");
        p66.add(jLabel140, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel141.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel141.setText("T1");
        p66.add(jLabel141, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel142.setText("$ 36.000");
        p66.add(jLabel142, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel143.setText("02:00 pm - 11:00pm");
        p66.add(jLabel143, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p66, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        p65.setBackground(new java.awt.Color(255, 255, 255));
        p65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p65.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel136.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel136.setText("1");
        p65.add(jLabel136, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel137.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel137.setText("T1");
        p65.add(jLabel137, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel138.setText("$ 36.000");
        p65.add(jLabel138, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel139.setText("02:00 pm - 11:00pm");
        p65.add(jLabel139, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p65, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        p69.setBackground(new java.awt.Color(255, 255, 255));
        p69.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p69.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel152.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel152.setText("1");
        p69.add(jLabel152, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel153.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel153.setText("T1");
        p69.add(jLabel153, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel154.setText("$ 36.000");
        p69.add(jLabel154, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel155.setText("02:00 pm - 11:00pm");
        p69.add(jLabel155, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p69, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, -1));

        p62.setBackground(new java.awt.Color(255, 255, 255));
        p62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p62.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel124.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel124.setText("1");
        p62.add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel125.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel125.setText("T1");
        p62.add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel126.setText("$ 36.000");
        p62.add(jLabel126, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel127.setText("02:00 pm - 11:00pm");
        p62.add(jLabel127, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p62, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, -1));

        p63.setBackground(new java.awt.Color(255, 255, 255));
        p63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p63.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel128.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel128.setText("1");
        p63.add(jLabel128, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel129.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel129.setText("T1");
        p63.add(jLabel129, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel130.setText("$ 36.000");
        p63.add(jLabel130, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel131.setText("02:00 pm - 11:00pm");
        p63.add(jLabel131, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p63, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        p70.setBackground(new java.awt.Color(255, 255, 255));
        p70.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p70.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel156.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel156.setText("1");
        p70.add(jLabel156, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel157.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel157.setText("T1");
        p70.add(jLabel157, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel158.setText("$ 36.000");
        p70.add(jLabel158, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel159.setText("02:00 pm - 11:00pm");
        p70.add(jLabel159, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p70, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, -1, -1));

        p61.setBackground(new java.awt.Color(255, 255, 255));
        p61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p61.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel120.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel120.setText("1");
        p61.add(jLabel120, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel121.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel121.setText("T1");
        p61.add(jLabel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel122.setText("$ 36.000");
        p61.add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel123.setText("02:00 pm - 11:00pm");
        p61.add(jLabel123, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p61, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, -1, -1));

        p68.setBackground(new java.awt.Color(255, 255, 255));
        p68.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p68.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel148.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel148.setText("1");
        p68.add(jLabel148, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel149.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel149.setText("T1");
        p68.add(jLabel149, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel150.setText("$ 36.000");
        p68.add(jLabel150, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel151.setText("02:00 pm - 11:00pm");
        p68.add(jLabel151, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p68, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        p71.setBackground(new java.awt.Color(255, 255, 255));
        p71.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p71.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel160.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel160.setText("1");
        p71.add(jLabel160, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel161.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel161.setText("T1");
        p71.add(jLabel161, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel162.setText("$ 36.000");
        p71.add(jLabel162, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel163.setText("02:00 pm - 11:00pm");
        p71.add(jLabel163, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p71, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, -1, -1));

        p72.setBackground(new java.awt.Color(255, 255, 255));
        p72.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p72.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel164.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel164.setText("1");
        p72.add(jLabel164, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel165.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel165.setText("T1");
        p72.add(jLabel165, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel166.setText("$ 36.000");
        p72.add(jLabel166, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel167.setText("02:00 pm - 11:00pm");
        p72.add(jLabel167, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p72, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, -1, -1));

        p73.setBackground(new java.awt.Color(255, 255, 255));
        p73.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p73.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel168.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel168.setText("1");
        p73.add(jLabel168, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel169.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel169.setText("T1");
        p73.add(jLabel169, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel170.setText("$ 36.000");
        p73.add(jLabel170, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel171.setText("02:00 pm - 11:00pm");
        p73.add(jLabel171, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p73, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, -1));

        p74.setBackground(new java.awt.Color(255, 255, 255));
        p74.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p74.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel172.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel172.setText("1");
        p74.add(jLabel172, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel173.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel173.setText("T1");
        p74.add(jLabel173, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel174.setText("$ 36.000");
        p74.add(jLabel174, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel175.setText("02:00 pm - 11:00pm");
        p74.add(jLabel175, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p74, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        p75.setBackground(new java.awt.Color(255, 255, 255));
        p75.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p75.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel176.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel176.setText("1");
        p75.add(jLabel176, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel177.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel177.setText("T1");
        p75.add(jLabel177, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel178.setText("$ 36.000");
        p75.add(jLabel178, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel179.setText("02:00 pm - 11:00pm");
        p75.add(jLabel179, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p75, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, -1, -1));

        p76.setBackground(new java.awt.Color(255, 255, 255));
        p76.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p76.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel180.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel180.setText("1");
        p76.add(jLabel180, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel181.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel181.setText("T1");
        p76.add(jLabel181, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel182.setText("$ 36.000");
        p76.add(jLabel182, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel183.setText("02:00 pm - 11:00pm");
        p76.add(jLabel183, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p76, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, -1, -1));

        p77.setBackground(new java.awt.Color(255, 255, 255));
        p77.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p77.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel184.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel184.setText("1");
        p77.add(jLabel184, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel185.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel185.setText("T1");
        p77.add(jLabel185, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel186.setText("$ 36.000");
        p77.add(jLabel186, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel187.setText("02:00 pm - 11:00pm");
        p77.add(jLabel187, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p77, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, -1, -1));

        p78.setBackground(new java.awt.Color(255, 255, 255));
        p78.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p78.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel188.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel188.setText("1");
        p78.add(jLabel188, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel189.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel189.setText("T1");
        p78.add(jLabel189, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel190.setText("$ 36.000");
        p78.add(jLabel190, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel191.setText("02:00 pm - 11:00pm");
        p78.add(jLabel191, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p78, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, -1, -1));

        p79.setBackground(new java.awt.Color(255, 255, 255));
        p79.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p79.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel192.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel192.setText("1");
        p79.add(jLabel192, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel193.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel193.setText("T1");
        p79.add(jLabel193, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel194.setText("$ 36.000");
        p79.add(jLabel194, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel195.setText("02:00 pm - 11:00pm");
        p79.add(jLabel195, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p79, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, -1, -1));

        p80.setBackground(new java.awt.Color(255, 255, 255));
        p80.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p80.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel196.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel196.setText("1");
        p80.add(jLabel196, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel197.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel197.setText("T1");
        p80.add(jLabel197, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel198.setText("$ 36.000");
        p80.add(jLabel198, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel199.setText("02:00 pm - 11:00pm");
        p80.add(jLabel199, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p80, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, -1, -1));

        p81.setBackground(new java.awt.Color(255, 255, 255));
        p81.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p81.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel200.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel200.setText("1");
        p81.add(jLabel200, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel201.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel201.setText("T1");
        p81.add(jLabel201, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel202.setText("$ 36.000");
        p81.add(jLabel202, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel203.setText("02:00 pm - 11:00pm");
        p81.add(jLabel203, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p81, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, -1, -1));

        p82.setBackground(new java.awt.Color(255, 255, 255));
        p82.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p82.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel204.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel204.setText("1");
        p82.add(jLabel204, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel205.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel205.setText("T1");
        p82.add(jLabel205, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel206.setText("$ 36.000");
        p82.add(jLabel206, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel207.setText("02:00 pm - 11:00pm");
        p82.add(jLabel207, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p82, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 480, -1, -1));

        p83.setBackground(new java.awt.Color(255, 255, 255));
        p83.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p83.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel208.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel208.setText("1");
        p83.add(jLabel208, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel209.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel209.setText("T1");
        p83.add(jLabel209, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel210.setText("$ 36.000");
        p83.add(jLabel210, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel211.setText("02:00 pm - 11:00pm");
        p83.add(jLabel211, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p83, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 480, -1, -1));

        p84.setBackground(new java.awt.Color(255, 255, 255));
        p84.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        p84.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel212.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel212.setText("1");
        p84.add(jLabel212, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));

        jLabel213.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel213.setText("T1");
        p84.add(jLabel213, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, -1));

        jLabel214.setText("$ 36.000");
        p84.add(jLabel214, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 10));

        jLabel215.setText("02:00 pm - 11:00pm");
        p84.add(jLabel215, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 20));

        jPanel2.add(p84, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 480, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("SABADO");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 80, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("DOMINGO");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("LUNES");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 60, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("MARTES");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 80, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("MIERCOLES");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 100, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("JUEVES");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 80, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("VIERNES");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 80, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 10, 30));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 10, 30));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 110, 30));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 0, 0, 30));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 10, 30));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 10, 30));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 10, 30));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 10, 30));

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 10, 30));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JLabel jLabel115;
    private javax.swing.JLabel jLabel116;
    private javax.swing.JLabel jLabel117;
    private javax.swing.JLabel jLabel118;
    private javax.swing.JLabel jLabel119;
    private javax.swing.JLabel jLabel120;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel123;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel126;
    private javax.swing.JLabel jLabel127;
    private javax.swing.JLabel jLabel128;
    private javax.swing.JLabel jLabel129;
    private javax.swing.JLabel jLabel130;
    private javax.swing.JLabel jLabel131;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel133;
    private javax.swing.JLabel jLabel134;
    private javax.swing.JLabel jLabel135;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JLabel jLabel155;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel jLabel158;
    private javax.swing.JLabel jLabel159;
    private javax.swing.JLabel jLabel160;
    private javax.swing.JLabel jLabel161;
    private javax.swing.JLabel jLabel162;
    private javax.swing.JLabel jLabel163;
    private javax.swing.JLabel jLabel164;
    private javax.swing.JLabel jLabel165;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JLabel jLabel167;
    private javax.swing.JLabel jLabel168;
    private javax.swing.JLabel jLabel169;
    private javax.swing.JLabel jLabel170;
    private javax.swing.JLabel jLabel171;
    private javax.swing.JLabel jLabel172;
    private javax.swing.JLabel jLabel173;
    private javax.swing.JLabel jLabel174;
    private javax.swing.JLabel jLabel175;
    private javax.swing.JLabel jLabel176;
    private javax.swing.JLabel jLabel177;
    private javax.swing.JLabel jLabel178;
    private javax.swing.JLabel jLabel179;
    private javax.swing.JLabel jLabel180;
    private javax.swing.JLabel jLabel181;
    private javax.swing.JLabel jLabel182;
    private javax.swing.JLabel jLabel183;
    private javax.swing.JLabel jLabel184;
    private javax.swing.JLabel jLabel185;
    private javax.swing.JLabel jLabel186;
    private javax.swing.JLabel jLabel187;
    private javax.swing.JLabel jLabel188;
    private javax.swing.JLabel jLabel189;
    private javax.swing.JLabel jLabel190;
    private javax.swing.JLabel jLabel191;
    private javax.swing.JLabel jLabel192;
    private javax.swing.JLabel jLabel193;
    private javax.swing.JLabel jLabel194;
    private javax.swing.JLabel jLabel195;
    private javax.swing.JLabel jLabel196;
    private javax.swing.JLabel jLabel197;
    private javax.swing.JLabel jLabel198;
    private javax.swing.JLabel jLabel199;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel200;
    private javax.swing.JLabel jLabel201;
    private javax.swing.JLabel jLabel202;
    private javax.swing.JLabel jLabel203;
    private javax.swing.JLabel jLabel204;
    private javax.swing.JLabel jLabel205;
    private javax.swing.JLabel jLabel206;
    private javax.swing.JLabel jLabel207;
    private javax.swing.JLabel jLabel208;
    private javax.swing.JLabel jLabel209;
    private javax.swing.JLabel jLabel210;
    private javax.swing.JLabel jLabel211;
    private javax.swing.JLabel jLabel212;
    private javax.swing.JLabel jLabel213;
    private javax.swing.JLabel jLabel214;
    private javax.swing.JLabel jLabel215;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLabel jLabel85;
    private javax.swing.JLabel jLabel86;
    private javax.swing.JLabel jLabel87;
    private javax.swing.JLabel jLabel88;
    private javax.swing.JLabel jLabel89;
    private javax.swing.JLabel jLabel90;
    private javax.swing.JLabel jLabel91;
    private javax.swing.JLabel jLabel92;
    private javax.swing.JLabel jLabel93;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JPanel p43;
    private javax.swing.JPanel p44;
    private javax.swing.JPanel p45;
    private javax.swing.JPanel p46;
    private javax.swing.JPanel p47;
    private javax.swing.JPanel p48;
    private javax.swing.JPanel p49;
    private javax.swing.JPanel p50;
    private javax.swing.JPanel p51;
    private javax.swing.JPanel p52;
    private javax.swing.JPanel p53;
    private javax.swing.JPanel p54;
    private javax.swing.JPanel p55;
    private javax.swing.JPanel p56;
    private javax.swing.JPanel p57;
    private javax.swing.JPanel p58;
    private javax.swing.JPanel p59;
    private javax.swing.JPanel p60;
    private javax.swing.JPanel p61;
    private javax.swing.JPanel p62;
    private javax.swing.JPanel p63;
    private javax.swing.JPanel p64;
    private javax.swing.JPanel p65;
    private javax.swing.JPanel p66;
    private javax.swing.JPanel p67;
    private javax.swing.JPanel p68;
    private javax.swing.JPanel p69;
    private javax.swing.JPanel p70;
    private javax.swing.JPanel p71;
    private javax.swing.JPanel p72;
    private javax.swing.JPanel p73;
    private javax.swing.JPanel p74;
    private javax.swing.JPanel p75;
    private javax.swing.JPanel p76;
    private javax.swing.JPanel p77;
    private javax.swing.JPanel p78;
    private javax.swing.JPanel p79;
    private javax.swing.JPanel p80;
    private javax.swing.JPanel p81;
    private javax.swing.JPanel p82;
    private javax.swing.JPanel p83;
    private javax.swing.JPanel p84;
    // End of variables declaration//GEN-END:variables
}
