/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import horaslaborales.AddRegistry;
import horaslaborales.DeductionsCalculator;
import horaslaborales.FieldString;
import horaslaborales.ManagingDataUser;
import horaslaborales.ManagingRegistry;
import horaslaborales.Sesion;
import java.util.Calendar;
import static java.util.Calendar.getInstance;
import java.util.Date;

/**
 *
 * @author Alejandro
 */
public class ConfigPane extends javax.swing.JPanel {

    /**
     * Creates new form HomePane
     */
    Sesion user;
    ManagingRegistry managing;
    ManagingDataUser managingData;
    
    public ConfigPane(Sesion user) {
        initComponents();
        this.user = user;
        managing = new ManagingRegistry(user);
        managingData = new ManagingDataUser(user);
        preconfig();
    }
    
         
     
    
    private void preconfig(){
        managing.getSalary(salary, user.getUser());
        labelUser.setText(user.getUser());
        editTerminationPayment.setText(FieldString.fieldNum(managingData.getTerminationPayment()));
        editBonuses.setText(FieldString.fieldNum(String.valueOf(managingData.getBonuses())));
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        labelUser = new javax.swing.JLabel();
        closeSesion = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        editTerminationPayment = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        editBonuses = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Dia de pago");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 130, -1));

        salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryActionPerformed(evt);
            }
        });
        salary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                salaryKeyReleased(evt);
            }
        });
        add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 144, 31));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("$");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 20, 30));

        labelUser.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labelUser.setText("user");
        add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 70, 20));

        closeSesion.setBackground(new java.awt.Color(0, 204, 0));
        closeSesion.setForeground(new java.awt.Color(255, 255, 255));
        closeSesion.setText("Cerrrar Sesion");
        closeSesion.setBorder(null);
        add(closeSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 80, 120, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_User_50px_2.png"))); // NOI18N
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 60, 40));
        add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 140, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Editar Sueldo");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 130, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Editar Cesantias");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 130, -1));

        editTerminationPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTerminationPaymentActionPerformed(evt);
            }
        });
        editTerminationPayment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                editTerminationPaymentKeyReleased(evt);
            }
        });
        add(editTerminationPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 144, 31));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("$");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 20, 30));

        jRadioButton1.setText("Quincenal");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, -1));

        jRadioButton2.setText("Semanal");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        jRadioButton3.setText("Mensual");
        add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Periodo de Pago de Nómina*");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 240, 44));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Editar Bonos Mensuales");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 170, -1));

        editBonuses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBonusesActionPerformed(evt);
            }
        });
        editBonuses.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                editBonusesKeyReleased(evt);
            }
        });
        add(editBonuses, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 144, 31));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("$");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 20, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryActionPerformed
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_salaryActionPerformed

    private void editTerminationPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTerminationPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editTerminationPaymentActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void salaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salaryKeyReleased
        // TODO add your handling code here:
        salary.setText(FieldString.fieldNum(salary.getText()));
         managing.updateLastSalary(salary);
    }//GEN-LAST:event_salaryKeyReleased

    private void editBonusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBonusesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_editBonusesActionPerformed

    private void editTerminationPaymentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editTerminationPaymentKeyReleased
        // TODO add your handling code here:
        editTerminationPayment.setText(FieldString.fieldNum(editTerminationPayment.getText()));
        managingData.updateTerminationPayment(FieldString.deleteWhiteSpaces(editTerminationPayment.getText()));
        
    }//GEN-LAST:event_editTerminationPaymentKeyReleased

    private void editBonusesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editBonusesKeyReleased
        // TODO add your handling code here:
        editBonuses.setText(FieldString.fieldNum(editBonuses.getText()));
        managingData.updateBonuses(FieldString.deleteWhiteSpaces(editBonuses.getText()));
    }//GEN-LAST:event_editBonusesKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeSesion;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextField editBonuses;
    private javax.swing.JTextField editTerminationPayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JLabel labelUser;
    private javax.swing.JTextField salary;
    // End of variables declaration//GEN-END:variables
}
