/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Inputs.FieldString;
import horaslaborales.ManagingDataUser;
import horaslaborales.ManagingRegistry;
import horaslaborales.Sesion;
import javax.swing.JTextField;

/**
 *
 * @author Alejandro
 */
public class ConfigPane extends javax.swing.JPanel {

    /**
     * Creates new form HomePane
     */
    Sesion user;
    ManagingRegistry managing;
    ManagingDataUser managingData;

    public ConfigPane(Sesion user) {
        initComponents();
        this.user = user;
        managing = new ManagingRegistry(user);
        managingData = new ManagingDataUser(user);
        preconfig();
    }

    private void preconfig() {
        managing.getSalary(salary, user.getUser());
       
        editTerminationPayment.setText(FieldString.fieldNum(managingData.getTerminationPayment()));
        editBonuses.setText(FieldString.fieldNum(String.valueOf(managingData.getBonuses())));

        switch (managingData.getPeriodsPayment()) {

            case 1:
                this.monthly.setSelected(true);
                break;

            case 2:
                this.biweekly.setSelected(true);
                break;

            case 4:
                this.weekly.setSelected(true);
                break;

            default:
                break;
        }

        if (managingData.getComision()) {
            this.jCheckBox3.setSelected(true);
        } else {
            this.jCheckBox4.setSelected(true);
        }

        if (managingData.getTransportAssistance()) {

            this.jCheckBox1.setSelected(true);
        } else {
            this.jCheckBox2.setSelected(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        editTerminationPayment = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        biweekly = new javax.swing.JRadioButton();
        weekly = new javax.swing.JRadioButton();
        monthly = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        editBonuses = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Dia de pago");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 130, -1));

        salary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                salaryKeyReleased(evt);
            }
        });
        add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 144, 31));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("$");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 20, 30));
        add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 140, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Editar Sueldo");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 130, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Editar Cesantias");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 130, -1));

        editTerminationPayment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                editTerminationPaymentKeyReleased(evt);
            }
        });
        add(editTerminationPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 144, 31));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("$");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 20, 30));

        buttonGroup1.add(biweekly);
        biweekly.setText("Quincenal");
        biweekly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biweeklyActionPerformed(evt);
            }
        });
        add(biweekly, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, -1));

        buttonGroup1.add(weekly);
        weekly.setText("Semanal");
        weekly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weeklyActionPerformed(evt);
            }
        });
        add(weekly, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        buttonGroup1.add(monthly);
        monthly.setText("Mensual");
        monthly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyActionPerformed(evt);
            }
        });
        add(monthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Periodo de Pago de Nómina*");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 240, 44));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Editar Bonos Mensuales");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 170, -1));

        editBonuses.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                editBonusesKeyReleased(evt);
            }
        });
        add(editBonuses, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 144, 31));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("$");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 20, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Auxilio de transporte");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 150, 20));

        buttonGroup3.add(jCheckBox1);
        jCheckBox1.setText("Si");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, -1, -1));

        buttonGroup3.add(jCheckBox2);
        jCheckBox2.setText("No");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Comisiones");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 150, 20));

        buttonGroup2.add(jCheckBox3);
        jCheckBox3.setText("Si");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));

        buttonGroup2.add(jCheckBox4);
        jCheckBox4.setText("No");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void biweeklyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biweeklyActionPerformed
        // TODO add your handling code here:
        managingData.updatePeriodsPayment(2);
    }//GEN-LAST:event_biweeklyActionPerformed

    private void weeklyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weeklyActionPerformed
        // TODO add your handling code here:
        managingData.updatePeriodsPayment(4);
    }//GEN-LAST:event_weeklyActionPerformed

    private void salaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salaryKeyReleased
        // TODO add your handling code here:
        int caretPosition = salary.getCaretPosition();
        salary.setText(FieldString.fieldNum(salary.getText()));
        FieldString.moveCaret(caretPosition, salary, evt);
        managing.updateLastSalary(salary);
    }//GEN-LAST:event_salaryKeyReleased

    private void editTerminationPaymentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editTerminationPaymentKeyReleased
        // TODO add your handling code here:

        int caretPosition = editTerminationPayment.getCaretPosition();
        editTerminationPayment.setText(FieldString.fieldNum(editTerminationPayment.getText()));

        FieldString.moveCaret(caretPosition, editTerminationPayment, evt);
        managingData.updateTerminationPayment(FieldString.deleteWhiteSpaces(editTerminationPayment.getText()));

    }//GEN-LAST:event_editTerminationPaymentKeyReleased

    private void editBonusesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editBonusesKeyReleased
        // TODO add your handling code here:
        int caretPosition = editBonuses.getCaretPosition();

        editBonuses.setText(FieldString.fieldNum(editBonuses.getText()));
        FieldString.moveCaret(caretPosition, editBonuses, evt);
        managingData.updateBonuses(FieldString.deleteWhiteSpaces(editBonuses.getText()));
    }//GEN-LAST:event_editBonusesKeyReleased

    private void monthlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyActionPerformed
        // TODO add your handling code here:
        managingData.updatePeriodsPayment(1);
    }//GEN-LAST:event_monthlyActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        managingData.updateTransportAssistance(true);
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
        managingData.updateComisions(true);
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
        managingData.updateComisions(false);
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        managingData.updateTransportAssistance(false);
    }//GEN-LAST:event_jCheckBox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton biweekly;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextField editBonuses;
    private javax.swing.JTextField editTerminationPayment;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton monthly;
    private javax.swing.JTextField salary;
    private javax.swing.JRadioButton weekly;
    // End of variables declaration//GEN-END:variables

    
}
