/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import horaslaborales.Sesion;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Alejandro
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    Sesion user;

    public MainWindow(Sesion ses) {
        initComponents();
        this.user = ses;
        MouseEvent ev = null;
        this.btn_HomeMousePressed(ev);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parent = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        btn_Home = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        border1 = new javax.swing.JPanel();
        btn_History = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        border2 = new javax.swing.JPanel();
        btn_About = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        border3 = new javax.swing.JPanel();
        btn_Config = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        border4 = new javax.swing.JPanel();
        background = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 600));
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        parent.setMinimumSize(new java.awt.Dimension(1000, 600));
        parent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(0, 204, 51));
        sidepane.setMinimumSize(new java.awt.Dimension(600, 200));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Home.setBackground(new java.awt.Color(0, 204, 51));
        btn_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_HomeMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Home_24px.png"))); // NOI18N

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Inicio");

        border1.setOpaque(false);
        border1.setPreferredSize(new java.awt.Dimension(5, 0));

        javax.swing.GroupLayout border1Layout = new javax.swing.GroupLayout(border1);
        border1.setLayout(border1Layout);
        border1Layout.setHorizontalGroup(
            border1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        border1Layout.setVerticalGroup(
            border1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btn_HomeLayout = new javax.swing.GroupLayout(btn_Home);
        btn_Home.setLayout(btn_HomeLayout);
        btn_HomeLayout.setHorizontalGroup(
            btn_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_HomeLayout.createSequentialGroup()
                .addComponent(border1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        btn_HomeLayout.setVerticalGroup(
            btn_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(border1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_HomeLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(26, 26, 26))
        );

        sidepane.add(btn_Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, 70));

        btn_History.setBackground(new java.awt.Color(0, 204, 51));
        btn_History.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_HistoryMousePressed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Calendar_24px.png"))); // NOI18N

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Registros");

        border2.setOpaque(false);
        border2.setPreferredSize(new java.awt.Dimension(5, 0));

        javax.swing.GroupLayout border2Layout = new javax.swing.GroupLayout(border2);
        border2.setLayout(border2Layout);
        border2Layout.setHorizontalGroup(
            border2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        border2Layout.setVerticalGroup(
            border2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btn_HistoryLayout = new javax.swing.GroupLayout(btn_History);
        btn_History.setLayout(btn_HistoryLayout);
        btn_HistoryLayout.setHorizontalGroup(
            btn_HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_HistoryLayout.createSequentialGroup()
                .addComponent(border2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        btn_HistoryLayout.setVerticalGroup(
            btn_HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addComponent(border2, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btn_HistoryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(23, 23, 23))
        );

        sidepane.add(btn_History, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 210, 70));

        btn_About.setBackground(new java.awt.Color(0, 204, 51));
        btn_About.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_AboutMousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_About_24px.png"))); // NOI18N

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Informacion");

        border3.setOpaque(false);
        border3.setPreferredSize(new java.awt.Dimension(5, 0));

        javax.swing.GroupLayout border3Layout = new javax.swing.GroupLayout(border3);
        border3.setLayout(border3Layout);
        border3Layout.setHorizontalGroup(
            border3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        border3Layout.setVerticalGroup(
            border3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btn_AboutLayout = new javax.swing.GroupLayout(btn_About);
        btn_About.setLayout(btn_AboutLayout);
        btn_AboutLayout.setHorizontalGroup(
            btn_AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_AboutLayout.createSequentialGroup()
                .addComponent(border3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        btn_AboutLayout.setVerticalGroup(
            btn_AboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addComponent(border3, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addGroup(btn_AboutLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sidepane.add(btn_About, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 210, 70));

        btn_Config.setBackground(new java.awt.Color(0, 204, 51));
        btn_Config.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_ConfigMousePressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Settings_24px_1.png"))); // NOI18N

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Configuraciones");

        border4.setOpaque(false);
        border4.setPreferredSize(new java.awt.Dimension(5, 0));

        javax.swing.GroupLayout border4Layout = new javax.swing.GroupLayout(border4);
        border4.setLayout(border4Layout);
        border4Layout.setHorizontalGroup(
            border4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        border4Layout.setVerticalGroup(
            border4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout btn_ConfigLayout = new javax.swing.GroupLayout(btn_Config);
        btn_Config.setLayout(btn_ConfigLayout);
        btn_ConfigLayout.setHorizontalGroup(
            btn_ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ConfigLayout.createSequentialGroup()
                .addComponent(border4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        btn_ConfigLayout.setVerticalGroup(
            btn_ConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(border4, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addGroup(btn_ConfigLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel8)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        sidepane.add(btn_Config, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, -1, -1));

        parent.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 600));

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        parent.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 900, 600));

        getContentPane().add(parent, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 1110, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_HomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HomeMousePressed
        // TODO add your handling code here:
        setColor(btn_Home);
        resetColor(btn_History);
        resetColor(btn_About);
        resetColor(btn_Config);
        //resetColor(btn_Search);
        opaqueBorder();
        border1.setOpaque(true);
        showHome();
    }//GEN-LAST:event_btn_HomeMousePressed

    private void btn_HistoryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HistoryMousePressed
        // TODO add your handling code here:
        setColor(btn_History);
        resetColor(btn_Home);
        resetColor(btn_About);
        resetColor(btn_Config);
        //resetColor(btn_Search);
        opaqueBorder();
        border2.setOpaque(true);
        showHistory();
    }//GEN-LAST:event_btn_HistoryMousePressed

    private void btn_AboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AboutMousePressed
        // TODO add your handling code here:
        setColor(btn_About);
        resetColor(btn_Home);
        resetColor(btn_History);
        resetColor(btn_Config);
        opaqueBorder();
        border3.setOpaque(true);
        showAbout();

    }//GEN-LAST:event_btn_AboutMousePressed

    private void btn_ConfigMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ConfigMousePressed
        // TODO add your handling code here:
        setColor(btn_Config);
        resetColor(btn_Home);
        resetColor(btn_History);
        resetColor(btn_About);
        opaqueBorder();
        border4.setOpaque(true);
        showConfig();
    }//GEN-LAST:event_btn_ConfigMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JPanel border1;
    private javax.swing.JPanel border2;
    private javax.swing.JPanel border3;
    private javax.swing.JPanel border4;
    private javax.swing.JPanel btn_About;
    private javax.swing.JPanel btn_Config;
    private javax.swing.JPanel btn_History;
    private javax.swing.JPanel btn_Home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel parent;
    private javax.swing.JPanel sidepane;
    // End of variables declaration//GEN-END:variables

    private void resetColor(JPanel panel) {

        panel.setBackground(new Color(0, 204, 51));
    }

    private void setColor(JPanel panel) {

        panel.setBackground(new Color(3, 236, 58));
    }

    private void opaqueBorder() {

        border1.setOpaque(false);
        border2.setOpaque(false);
        border3.setOpaque(false);
        border4.setOpaque(false);
    }

    private void showAbout() {

        background.removeAll();
        InfoPane info = new InfoPane(this.user);
        info.setVisible(true);
        JButton close = (JButton) info.getComponent(1);
        close.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SesionWindow sw = new SesionWindow();
                sw.setLocationRelativeTo(null);
                sw.setVisible(true);
                close();
            }

        });
        background.add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        background.updateUI();
    }

    private void showConfig() {

        background.removeAll();
        ConfigPane config = new ConfigPane(this.user);
        config.setVisible(true);
        JButton close = (JButton) config.getComponent(4);
        close.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SesionWindow sw = new SesionWindow();
                sw.setLocationRelativeTo(null);
                sw.setVisible(true);
                close();
            }

        });
        background.add(config, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));
        background.updateUI();

    }

    private void showHistory() {
        background.removeAll();
        HistoryPane history = new HistoryPane(user);
        background.setVisible(true);
        background.add(history, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));
        background.updateUI();

    }

    private void showHome() {

        background.removeAll();
        HomePane home = new HomePane(this.user);
        home.setVisible(true);
        JButton close = (JButton) home.getComponent(27);
        close.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SesionWindow sw = new SesionWindow();
                sw.setLocationRelativeTo(null);
                sw.setVisible(true);
                close();
            }

        });
        background.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));
        background.updateUI();
    }

    private void close() {
        dispose();
    }

}
