/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Inputs.VerifiedAddRegistry;
import horaslaborales.Calculator;
import horaslaborales.ManagingDataUser;
import horaslaborales.InterfaceHistory;
import models.Registry;
import horaslaborales.Sesion;
import models.Turn;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Alejandro
 */
public class RegistryPane extends javax.swing.JPanel {

    /**
     * Creates new form RegistryPane
     */
    Registry registry;
    InterfaceHistory managing;
    ManagingDataUser managingData;
    Sesion user;
    VerifiedAddRegistry verifiedRegistry;
    ArrayList<Turn> turnsUser;
    AddRegistry wregistry;
    
    
    
    public RegistryPane(Sesion user, AddRegistry wregistry) {
        this.user = user;
        this.wregistry = wregistry;
        initComponents();
        managing = new InterfaceHistory(user);
        managingData = new ManagingDataUser(user);
        preConfigureWindow();

    }

    public RegistryPane(Registry reg, Sesion user, AddRegistry wregistry) {
        initComponents();
        this.user = user;
        this.registry = reg;
        this.wregistry = wregistry;
        
        managing = new InterfaceHistory(user);
        managingData = new ManagingDataUser(user);
        
        preConfigureWindow();
        preChargedData();
    }

    private int getTimeChooser(JComboBox combo) {
        int select = combo.getSelectedIndex();

        if (select == 0) {
            if (verifiedRegistry.selectTypeDay() == 3 | verifiedRegistry.selectTypeDay() == 4) {
                return 0;
            } else {
                return 24;
            }
        } else {
            return select;
        }
    }

    private void preConfigureWindow() {

        managing.getSalary(salary, user.getUser());

        //Edit Table contents
        
        turnsUser = managingData.getTurns();
        
        for (Turn turn : turnsUser) {
            
            turns.addItem(turn.getNameTurn());
        }
        
        //
        date2.setEnabled(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Tipo Hora", "Cantidad", "Costo"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });

        verifiedRegistry = new VerifiedAddRegistry(this.time1, time2, date1, date2);
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private String nameHours(int i) {
        String[] nameHours = new String[11];
        nameHours[0] = "H. Ordinarias";
        nameHours[1] = "H. Recargo";
        nameHours[2] = "H. Extra Diurna";
        nameHours[3] = "H. Extra Recargo";
        nameHours[4] = "Total Horas Dia 1 ";
        nameHours[5] = "H. Dominical Festivo";
        nameHours[6] = "H. Dominical Festivo Recargo";
        nameHours[7] = "H. Dominical Festivo Ex. Diurno";
        nameHours[8] = "H. Dominical Festivo Ex. Recargo";
        nameHours[9] = "Total Horas Dia 2";
        nameHours[10] = "TOTAL:";

        return nameHours[i];
    }

    private void preChargedData() {
        if (registry != null) {
            this.date1.setDate(registry.getStartDay());
            this.date2.setDate(registry.getFinishDay());
            date1.setSelectableDateRange(registry.getStartDay(), registry.getStartDay());
            
            time1.setSelectedItem(registry.getTime_startDay());
            time2.setSelectedItem(registry.getTime_finishDay());
 
            date2.setEnabled(true);
            verifiedRegistry.updateDates();
            
        }
    }

    private void showData(Calculator calc) {

        if (jTable1.getSize().height > 0) {

        }

        double[] costo = calc.calcularSueldo();
        calc.setContT(0);
        int[] horas = calc.calcularHoras();
        DefaultTableModel table = (DefaultTableModel) this.jTable1.getModel();
        table.setNumRows(0);

        int n = horas.length;

        for (int i = 0; i < n; i++) {

            if (horas[i] != 0) {

                //Mostrar primero info domingo o festivo
                if (n > 5 & verifiedRegistry.selectTypeDay() == 4) {
                    if (i < 5) {

                        if (i != 4) {
                            table.addRow(new Object[]{nameHours(i + 5), horas[i], costo[i]});
                        } else
                            table.addRow(new Object[]{nameHours(i), horas[i], costo[i]});

                    } else {
                        if (i < 9) {
                            table.addRow(new Object[]{nameHours(i - 5), horas[i], costo[i]});
                        } else {
                            table.addRow(new Object[]{nameHours(i), horas[i], costo[i]});
                        }

                    }

                    //Mostrar info turno de dos dias ordinario
                } else if (getTimeChooser(time2) < getTimeChooser(time1) & verifiedRegistry.selectTypeDay() == 1) {

                    if (i > 4 & i < 9) {
                        table.addRow(new Object[]{nameHours(i - 5), horas[i], costo[i]});
                    } else {
                        table.addRow(new Object[]{nameHours(i), horas[i], costo[i]});
                    }

                    //Fostrar info festivo
                } else if (verifiedRegistry.selectTypeDay() == 2){

                    
                    if (i != 4) {
                          
                        table.addRow(new Object[]{nameHours(i + 5), horas[i], costo[i]});
                        } else
                            table.addRow(new Object[]{nameHours(i), horas[i], costo[i]});
                } else{
                    
                    table.addRow(new Object[]{nameHours(i), horas[i], costo[i]});
                }
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salary = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        calculate = new javax.swing.JButton();
        date1 = new com.toedter.calendar.JDateChooser();
        date2 = new com.toedter.calendar.JDateChooser();
        turns = new javax.swing.JComboBox<>();
        saveRegistry = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        startToday = new javax.swing.JCheckBox();
        finishToday = new javax.swing.JCheckBox();
        time1 = new javax.swing.JComboBox<>();
        time2 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        salary.setEditable(false);
        salary.setBackground(new java.awt.Color(171, 235, 198));
        salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryActionPerformed(evt);
            }
        });
        salary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                salaryKeyPressed(evt);
            }
        });
        add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 110, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Sueldo");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 70, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Fecha/Hora Fin");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 160, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Fecha/Hora Inicio");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 170, 30));

        jTable1.setBackground(new java.awt.Color(130, 224, 170));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(171, 235, 198));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 480, 110));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Seleccione un turno");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, -1));

        calculate.setBackground(new java.awt.Color(0, 204, 51));
        calculate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        calculate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Calculator_24px.png"))); // NOI18N
        calculate.setText("Calcular");
        calculate.setFocusPainted(false);
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });
        add(calculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 120, 40));

        date1.setBackground(new java.awt.Color(171, 235, 198));
        date1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date1PropertyChange(evt);
            }
        });
        add(date1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 110, 30));

        date2.setBackground(new java.awt.Color(171, 235, 198));
        date2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                date2PropertyChange(evt);
            }
        });
        add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 110, 30));

        turns.setBackground(new java.awt.Color(171, 235, 198));
        turns.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        turns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnsActionPerformed(evt);
            }
        });
        add(turns, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 270, 30));

        saveRegistry.setBackground(new java.awt.Color(0, 204, 51));
        saveRegistry.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        saveRegistry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Save_24px.png"))); // NOI18N
        saveRegistry.setText("Guardar en Registro");
        saveRegistry.setFocusPainted(false);
        saveRegistry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveRegistryActionPerformed(evt);
            }
        });
        add(saveRegistry, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 420, -1, 40));

        cancel.setBackground(new java.awt.Color(0, 204, 51));
        cancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Cancel_24px.png"))); // NOI18N
        cancel.setText("Cancelar");
        cancel.setFocusPainted(false);
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 130, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("$");
        jLabel6.setAlignmentX(1.0F);
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 30, 30));

        startToday.setText("Hoy");
        startToday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTodayActionPerformed(evt);
            }
        });
        add(startToday, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        finishToday.setText("Hoy");
        finishToday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishTodayActionPerformed(evt);
            }
        });
        add(finishToday, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, -1, -1));

        time1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12 am", "01 am", "02 am", "03 am", "04 am", "05 am", "06 am", "07 am", "08 am", "09 am", "10 am", "11 am", "12 pm", "01 pm", "02 pm", "03 pm", "04 pm", "05 pm", "06 pm", "07 pm", "08 pm", "09 pm", "10 pm", "11 pm" }));
        add(time1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, 30));

        time2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12 am", "01 am", "02 am", "03 am", "04 am", "05 am", "06 am", "07 am", "08 am", "09 am", "10 am", "11 am", "12 pm", "01 pm", "02 pm", "03 pm", "04 pm", "05 pm", "06 pm", "07 pm", "08 pm", "09 pm", "10 pm", "11 pm" }));
        time2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                time2ActionPerformed(evt);
            }
        });
        add(time2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void salaryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salaryKeyPressed

    }//GEN-LAST:event_salaryKeyPressed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
        
        Calculator calc;
        jTable1.removeAll();
        jTable1.updateUI();
        verifiedRegistry.verifiedDates();   

        if (verifiedRegistry.verifiedEntries()) {
            
            
            String sal = this.salary.getText().replaceAll(" ", "");

            double i = Double.parseDouble(sal);
            calc = new Calculator(getTimeChooser(time1), getTimeChooser(time2), (int) i);
            
            
            if(date1.getCalendar().get(Calendar.DAY_OF_MONTH)!=date2.getCalendar().get(Calendar.DAY_OF_MONTH)){
                calc.setNextDay(true);
                
            } 
            
            calc.setDia(verifiedRegistry.selectTypeDay());
            showData(calc);

        }
    }//GEN-LAST:event_calculateActionPerformed

    private void date1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date1PropertyChange
        // TODO add your handling code here:

        if(verifiedRegistry!=null){
            verifiedRegistry.updateDates();
            date2.setEnabled(true);
        }

    }//GEN-LAST:event_date1PropertyChange

    private void date2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_date2PropertyChange
        // TODO add your handling code here:
        /*if (this.jDateChooser1.getCalendar() == null) {

            if (selectTypeDay.getSelectedIndex() > 1) {
                Calendar c = jDateChooser2.getCalendar();
                c.add(Calendar.DAY_OF_MONTH, -1);
                jDateChooser2.setCalendar(c);
            }

        }*/
    }//GEN-LAST:event_date2PropertyChange

    private void turnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnsActionPerformed
        // TODO add your handling code here:

        int numTurn = turns.getSelectedIndex();

        if(numTurn>=0){

            time1.setSelectedItem(turnsUser.get(numTurn-1).getHourStart());
            time2.setSelectedItem(turnsUser.get(numTurn-1).getHourFinish());

        }

    }//GEN-LAST:event_turnsActionPerformed

    private void saveRegistryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveRegistryActionPerformed
        // TODO add your handling code here:
        verifiedRegistry.verifiedDates();
        if (verifiedRegistry.verifiedEntries()) {

            String sal = this.salary.getText().replace(" ", "");
            double i = Double.parseDouble(sal);

            Calculator calc = new Calculator(getTimeChooser(time1), getTimeChooser(time2),
                (int) i);
            
            if(date1.getCalendar().get(Calendar.DAY_OF_MONTH)!=date2.getCalendar().get(Calendar.DAY_OF_MONTH)){
                calc.setNextDay(true);
                
            } 
            
            calc.setDia(verifiedRegistry.selectTypeDay());

            if (registry == null) {

                boolean h = managing.saveRegistry(this.date1, time1, this.date2, time2, calc);
                if (h) {
                    wregistry.dispose();
                }

            } else {

                managing.updateRegistry(date1,time1,date2, calc, time2);
                wregistry.dispose();

            }
            //managing.updateLastSalary(salary, "prueba");
            //dispose();

        }
    }//GEN-LAST:event_saveRegistryActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        wregistry.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void startTodayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTodayActionPerformed
        // TODO add your handling code here:

        Calendar calendarNow;
        calendarNow = Calendar.getInstance();
        this.date1.setCalendar(calendarNow);
    }//GEN-LAST:event_startTodayActionPerformed

    private void finishTodayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishTodayActionPerformed
        // TODO add your handling code here:
        Calendar calendarNow;
        calendarNow = Calendar.getInstance();
        this.date2.setCalendar(calendarNow);
    }//GEN-LAST:event_finishTodayActionPerformed

    private void time2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_time2ActionPerformed
        // TODO add your handling code here:
        verifiedRegistry.verifiedDates();
    }//GEN-LAST:event_time2ActionPerformed

    private void salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculate;
    private javax.swing.JButton cancel;
    private com.toedter.calendar.JDateChooser date1;
    private com.toedter.calendar.JDateChooser date2;
    private javax.swing.JCheckBox finishToday;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField salary;
    private javax.swing.JButton saveRegistry;
    private javax.swing.JCheckBox startToday;
    private javax.swing.JComboBox<String> time1;
    private javax.swing.JComboBox<String> time2;
    private javax.swing.JComboBox<String> turns;
    // End of variables declaration//GEN-END:variables
}
