/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Alejandro
 */
public class TwoTurnsPane extends javax.swing.JPanel {

    /**
     * Creates new form TwoTurnsPane
     */
    public TwoTurnsPane() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel287 = new javax.swing.JLabel();
        jLabel286 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        setMinimumSize(new java.awt.Dimension(120, 90));
        setPreferredSize(new java.awt.Dimension(120, 90));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(153, 233, 79));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 44, 173, -1));

        jLabel287.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel287.setText("11:00 pm - 07:00am");
        add(jLabel287, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        jLabel286.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel286.setText("$ 36.000");
        add(jLabel286, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 50, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("T2");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 20, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Fin -07:00 am");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("T2");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setText("1");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 10, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel286;
    private javax.swing.JLabel jLabel287;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
