/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author Alejandro
 */
public class TwoTurnsPane extends javax.swing.JPanel {

    /**
     * Creates new form TwoTurnsPane
     */
    public TwoTurnsPane() {
        initComponents();
        clean();
    }
    
    private void clean(){
        
        this.day.setText("");
        this.hourDay1.setText("");
        this.hourDay2.setText("");
        this.money.setText("");
        this.turnDay1.setText("");
        this.turnDay2.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void setDay(String day){
       
        this.day.setText(day);
        this.day.setForeground(new java.awt.Color(0, 0, 0));
    }
    
    public void setTurnDay1(String turn){
        
        this.turnDay1.setText(turn);
    }
    
    public void setHourDay1(String hour){
        
        this.hourDay1.setText(hour);
        
    }
    
    public void setTurnDay2(String turn){
        
        this.turnDay2.setText(turn);
    }
    
    public void setHourDay2(String hour){
        
        this.hourDay2.setText(hour);
        
    }
    
    public void setMoney(String money){
        
       this.money.setText(money);
    }
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        hourDay2 = new javax.swing.JLabel();
        money = new javax.swing.JLabel();
        turnDay2 = new javax.swing.JLabel();
        hourDay1 = new javax.swing.JLabel();
        turnDay1 = new javax.swing.JLabel();
        day = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 233, 79)));
        setMinimumSize(new java.awt.Dimension(120, 90));
        setPreferredSize(new java.awt.Dimension(120, 90));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setForeground(new java.awt.Color(153, 233, 79));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 44, 173, -1));

        hourDay2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hourDay2.setText("11:00 pm - 07:00am");
        add(hourDay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 120, 20));

        money.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        money.setText("$ 36.000");
        add(money, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 70, 10));

        turnDay2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        turnDay2.setText("T2");
        add(turnDay2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 20, 20));

        hourDay1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hourDay1.setText("Fin -07:00 am");
        add(hourDay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        turnDay1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        turnDay1.setText("T2");
        add(turnDay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        day.setBackground(new java.awt.Color(255, 255, 255));
        day.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        day.setText("1");
        add(day, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 20, 20));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel day;
    private javax.swing.JLabel hourDay1;
    private javax.swing.JLabel hourDay2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel money;
    private javax.swing.JLabel turnDay1;
    private javax.swing.JLabel turnDay2;
    // End of variables declaration//GEN-END:variables
}
