/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Questions;

import Inputs.FieldString;
import horaslaborales.Question;
import models.NewRegistry;


/**
 *
 * @author Alejandro
 */
public class Question2 extends javax.swing.JPanel implements Question{

    /**
     * Creates new form Pregunta2
     */
    NewRegistry reg = new NewRegistry();

    public Question2(NewRegistry reg) {
        initComponents();
        this.reg = reg;
        reg.setMensualBonuses("0");
        reg.setTerminationPayment("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        terminationPayment = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bonuses = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(480, 260));
        setPreferredSize(new java.awt.Dimension(480, 260));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cesantías");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 91, 27));

        terminationPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminationPaymentActionPerformed(evt);
            }
        });
        terminationPayment.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                terminationPaymentKeyReleased(evt);
            }
        });
        add(terminationPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 160, 28));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("$");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 20, 20));

        jLabel4.setBackground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("(Colocar el monto de cesantías que tiene hasta el momento)");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 290, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Bonos Fijos Mensuales");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 220, 44));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("$");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 20, 20));

        jLabel6.setBackground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("(Si recibe bonos fijos mesuales llenar este campo)");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 250, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Bonos Fijos Mensuales");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 220, 44));

        bonuses.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bonusesKeyReleased(evt);
            }
        });
        add(bonuses, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 170, 30));

        jLabel8.setBackground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("(Si recibe bonos fijos mesuales llenar este campo)");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 250, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void terminationPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminationPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_terminationPaymentActionPerformed

    private void terminationPaymentKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_terminationPaymentKeyReleased
        // TODO add your handling code here:
        int caretPosition = terminationPayment.getCaretPosition();
        terminationPayment.setText(FieldString.fieldNum(terminationPayment.getText()));
        FieldString.moveCaret(caretPosition, bonuses, evt);
        reg.setTerminationPayment(FieldString.deleteWhiteSpaces(terminationPayment.getText()));
    }//GEN-LAST:event_terminationPaymentKeyReleased

    private void bonusesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bonusesKeyReleased
        // TODO add your handling code here:
        int caretPosition = bonuses.getCaretPosition();
        bonuses.setText(FieldString.fieldNum(bonuses.getText()));
        FieldString.moveCaret(caretPosition, bonuses, evt);
        
        reg.setMensualBonuses(FieldString.deleteWhiteSpaces(this.bonuses.getText()));
        
    }//GEN-LAST:event_bonusesKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bonuses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField terminationPayment;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean hasNullInputs() {

        return false;
    }
}
