/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Questions;

import Inputs.FieldString;
import horaslaborales.Question;
import java.awt.Color;
import javax.swing.JLabel;
import models.NewRegistry;

/**
 *
 * @author Alejandro
 */
public class Question0 extends javax.swing.JPanel  implements Question{

    /**
     * Creates new form Pregunta2
     */
    
    NewRegistry reg;
    public Question0(NewRegistry reg) {
        initComponents();
        this.reg = reg;
        
        preconfig();
    }
    
    private void preconfig(){
        
        if(reg.getName()!=null){
            nameUser.setText(reg.getName());
        } 
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        nameUser = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(480, 260));
        setPreferredSize(new java.awt.Dimension(480, 260));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nombre y Apellido");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 140, 30));

        nameUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameUserActionPerformed(evt);
            }
        });
        nameUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameUserKeyReleased(evt);
            }
        });
        add(nameUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 203, 34));
    }// </editor-fold>//GEN-END:initComponents

    private void nameUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameUserKeyReleased
        // TODO add your handling code here:
        reg.setName(this.nameUser.getText().trim().replaceAll(" ", ""));
    }//GEN-LAST:event_nameUserKeyReleased

    private void nameUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameUserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nameUser;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean hasNullInputs() {

        return false;
          
    }
}
