/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Questions;

import Inputs.FieldString;
import horaslaborales.Question;
import java.awt.Color;
import javax.swing.JLabel;
import models.NewRegistry;

/**
 *
 * @author Alejandro
 */
public class Question1 extends javax.swing.JPanel  implements Question{

    /**
     * Creates new form Pregunta2
     */
    
    NewRegistry reg;
    public Question1(NewRegistry reg) {
        initComponents();
        this.reg = reg;
        
        preconfig();
    }
    
    private void preconfig(){
        
        if(reg.getSalary()==(null)){
            
            reg.setPeriods_payment(1);
        } else{
            
            salary.setText(FieldString.fieldNum(reg.getSalary()));
            switch(reg.getPeriods_payment()){
                
                case 1:
                    monthly.setSelected(true);
                    break;
                    
                case 2:
                    biweekly.setSelected(true);
                    break;
                    
                default:
                    weekly.setSelected(true);
                    break;
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel8 = new javax.swing.JLabel();
        biweekly = new javax.swing.JRadioButton();
        weekly = new javax.swing.JRadioButton();
        monthly = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        message = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(480, 260));
        setPreferredSize(new java.awt.Dimension(480, 260));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Salario basico*");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 240, 44));

        buttonGroup1.add(biweekly);
        biweekly.setText("Quincenal");
        biweekly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biweeklyActionPerformed(evt);
            }
        });
        add(biweekly, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        buttonGroup1.add(weekly);
        weekly.setText("Semanal");
        weekly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weeklyActionPerformed(evt);
            }
        });
        add(weekly, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        buttonGroup1.add(monthly);
        monthly.setText("Mensual");
        monthly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthlyActionPerformed(evt);
            }
        });
        add(monthly, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Periodo de Pago de Nómina*");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 240, 44));

        salary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                salaryKeyReleased(evt);
            }
        });
        add(salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 140, 28));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("$");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 20, 20));
        add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 90, -30));
    }// </editor-fold>//GEN-END:initComponents

    private void weeklyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weeklyActionPerformed
        // TODO add your handling code here:
        reg.setPeriods_payment(4);
    }//GEN-LAST:event_weeklyActionPerformed

    private void salaryKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_salaryKeyReleased
        // TODO add your handling code here:
        int caretProsition = salary.getCaretPosition();
        salary.setText(FieldString.fieldNum(salary.getText()));
        FieldString.moveCaret(caretProsition, salary, evt);
        reg.setSalary(FieldString.deleteWhiteSpaces(salary.getText()));
    }//GEN-LAST:event_salaryKeyReleased

    private void monthlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthlyActionPerformed
        // TODO add your handling code here:
        reg.setPeriods_payment(1);
    }//GEN-LAST:event_monthlyActionPerformed

    private void biweeklyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biweeklyActionPerformed
        // TODO add your handling code here:
        reg.setPeriods_payment(2);
    }//GEN-LAST:event_biweeklyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton biweekly;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel message;
    private javax.swing.JRadioButton monthly;
    private javax.swing.JTextField salary;
    private javax.swing.JRadioButton weekly;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean hasNullInputs() {

        if( this.salary.getText().equals("")){
            
            message.setText("Escriba el sueldo");
            message.setForeground(Color.red);
            this.add(message,new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70));
            return true;
        } else 
          
            return false;
          
    }
}
